export interface PhetSim {
  slug: string;           // URL slug (mevcut: 'atom-olustur', yeni: 'faraday-kanunu')
  phet_id: string;        // PhET orijinal ID: 'build-an-atom'
  title_tr: string;       // Türkçe başlık
  description: string;
  category: 'TYT' | 'AYT' | 'TYT/AYT';
  subject: 'Fizik' | 'Kimya' | 'Biyoloji' | 'Matematik' | 'Genel';
  topic: string;
  difficulty_level: 1 | 2 | 3 | 4 | 5;
  related_yks_topics: string[];
  badge?: string;
  has_turkish: boolean;   // locale=tr çalışıyor mu
  is_active: boolean;
}

// PhET URL yardımcısı
export function getPhetUrl(phet_id: string, has_turkish: boolean): string {
  const locale = has_turkish ? '?locale=tr' : '';
  return `https://phet.colorado.edu/sims/html/${phet_id}/latest/${phet_id}_all.html${locale}`;
}

export const PHET_REGISTRY: PhetSim[] = [
  // ─── FİZİK (52 simülasyon) ────────────────────────────────────────────────
  // Mevcut 52 simülasyon (slug aynı kalıyor, phet_id ekleniyor)
  { slug: 'atom-olustur', phet_id: 'build-an-atom', title_tr: 'Atom Oluştur', description: 'Proton, nötron ve elektron ekleyerek atomları oluştur, element, sembol ve kütleyi keşfet.', category: 'AYT', subject: 'Kimya', topic: 'Atom Yapısı', difficulty_level: 2, related_yks_topics: ['Atom Yapısı', 'Element Sembolleri', 'İyon Oluşumu'], badge: 'AYT Kimya', has_turkish: true, is_active: true },
  { slug: 'doppler-etkisi', phet_id: 'wave-on-a-string', title_tr: 'Doppler Etkisi', description: 'Hareketli ses kaynağının dalga boyunu sıkıştırması, frekans kayması ve algılanan ses perdesi deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Dalgalar', difficulty_level: 3, related_yks_topics: ['Doppler Olayı', 'Ses Dalgaları', 'Frekans Kayması'], badge: 'AYT Banko Soru', has_turkish: true, is_active: true },
  { slug: 'sigac-kondansator', phet_id: 'capacitor-lab-basics', title_tr: 'Kondansatör (Sığaç) & Dielektrik', description: 'Levhalar arası mesafe, dielektrik madde sokulması; pile bağlıyken ve pilden ayrılınca C, Q, V, E değişimi.', category: 'AYT', subject: 'Fizik', topic: 'Elektrostatik & Sığaçlar', difficulty_level: 4, related_yks_topics: ['Sığaçlar', 'Dielektrik Katsayısı', 'Depolanan Enerji'], badge: 'AYT Klasik Soru', has_turkish: true, is_active: true },
  { slug: 'fotoelektrik', phet_id: 'photoelectric', title_tr: 'Fotoelektrik Olayı', description: 'Farklı metallere farklı dalga boyunda foton düşürerek elektron sökülmesi ve kinetik enerji hesabı.', category: 'AYT', subject: 'Fizik', topic: 'Modern Fizik', difficulty_level: 4, related_yks_topics: ['Fotoelektrik', 'Eşik Enerjisi', 'Durdurma Gerilimi'], badge: 'Her Yıl 1 Soru', has_turkish: true, is_active: true },
  { slug: 'egik-atis', phet_id: 'projectile-motion', title_tr: 'İki Boyutta Eğik Atış', description: 'Başlangıç hızı, atış açısı ve yerçekimini değiştirerek uçuş süresi, menzil ve maksimum yükseklik deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Kuvvet ve Hareket', difficulty_level: 3, related_yks_topics: ['Atışlar', 'Eğik Atış', 'Maksimum Yükseklik'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'young-deneyi', phet_id: 'wave-interference', title_tr: 'Young Çift Yarıkta Girişim', description: 'Işığın dalga doğası, aydınlık/karanlık saçaklar, yarıklar arası mesafe ve dalga boyu ilişkisi.', category: 'AYT', subject: 'Fizik', topic: 'Dalga Optiği', difficulty_level: 4, related_yks_topics: ['Çift Yarık', 'Saçak Genişliği', 'Kırınım'], badge: 'AYT Optik', has_turkish: true, is_active: true },
  { slug: 'isigin-kirilmasi', phet_id: 'bending-light', title_tr: 'Işığın Kırılması & Snell', description: 'Farklı ortamlarda ışık kırılması, kritik açı, toplam yansıma ve Snell yasası deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Optik', difficulty_level: 3, related_yks_topics: ['Kırılma Yasası', 'Snell Yasası', 'Tam Yansıma'], badge: 'AYT Optik', has_turkish: true, is_active: true },
  { slug: 'elektrik-devresi', phet_id: 'circuit-construction-kit-dc', title_tr: 'Elektrik Devresi Yapıcı', description: 'Direnç, pil, ampermetre ve voltmetre ile seri/paralel devre kurma deneyi.', category: 'TYT', subject: 'Fizik', topic: 'Elektrik Devreleri', difficulty_level: 2, related_yks_topics: ['Seri Devre', 'Paralel Devre', 'Ohm Yasası'], badge: 'TYT/AYT', has_turkish: true, is_active: true },
  { slug: 'enerji-parki', phet_id: 'energy-skate-park', title_tr: 'Enerji Parkı (Kaykay)', description: 'Kinetik ve potansiyel enerji dönüşümü, sürtünmeli ve sürtünmesiz yüzeylerde mekanik enerji.', category: 'TYT', subject: 'Fizik', topic: 'Enerji', difficulty_level: 2, related_yks_topics: ['Mekanik Enerji', 'Enerji Dönüşümü', 'Sürtünme Kuvveti'], badge: 'TYT Banko Soru', has_turkish: true, is_active: true },
  { slug: 'kuvvet-ve-hareket', phet_id: 'forces-and-motion-basics', title_tr: 'Kuvvet ve Hareket Temelleri', description: 'Net kuvvet, ivme ve Newton 2. Yasası ilişkisini görsel interaktif deney.', category: 'TYT', subject: 'Fizik', topic: 'Kuvvet ve Hareket', difficulty_level: 1, related_yks_topics: ['Newton Yasaları', 'Net Kuvvet', 'İvme'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'momentum', phet_id: 'collision-lab', title_tr: 'Momentum & Çarpışmalar', description: 'Elastik ve plastik çarpışmalarda momentum korunumu ve kinetik enerji değişimi deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Momentum', difficulty_level: 3, related_yks_topics: ['Momentum Korunumu', 'Çarpışma Türleri', 'Kinetik Enerji'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'yay-dalgalari', phet_id: 'wave-on-a-string', title_tr: 'Yayda Dalga Hareketi', description: 'Gerilim, frekans ve genlik değiştirerek yayda transvers dalga ve durgun dalga oluşturma.', category: 'AYT', subject: 'Fizik', topic: 'Dalgalar', difficulty_level: 3, related_yks_topics: ['Transvers Dalgalar', 'Durgun Dalgalar', 'Rezonans'], badge: 'AYT Dalgalar', has_turkish: true, is_active: true },
  { slug: 'manyetik-induksiyon', phet_id: 'faradays-law', title_tr: 'Manyetik İndüksiyon', description: 'Faraday Yasası: mıknatıs-bobin hareketinde EMK oluşumu ve Lenz Yasası gözlemi.', category: 'AYT', subject: 'Fizik', topic: 'Elektromanyetik İndüksiyon', difficulty_level: 4, related_yks_topics: ['Faraday Yasası', 'EMK', 'Lenz Yasası'], badge: 'AYT Banko Soru', has_turkish: true, is_active: true },
  { slug: 'radyoaktif-bozunma', phet_id: 'nuclear-fission', title_tr: 'Radyoaktif Bozunma & Yarı Ömür', description: 'Alfa, beta, gama bozunması türleri ve yarı ömür grafiği ile nükleer kararlılık.', category: 'AYT', subject: 'Fizik', topic: 'Modern Fizik', difficulty_level: 4, related_yks_topics: ['Radyoaktif Bozunma', 'Yarı Ömür', 'Bozunma Türleri'], badge: 'AYT Modern Fizik', has_turkish: false, is_active: true },
  { slug: 'yari-omur', phet_id: 'radioactive-dating-game', title_tr: 'Yarı Ömür & Yaş Tayini', description: 'Karbon-14 ve Uranyum-238 ile radyoaktif yarı ömür ve fosil/kayaç yaş tayini deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Modern Fizik', difficulty_level: 4, related_yks_topics: ['Yarı Ömür', 'Karbon Tayini', 'Radyoaktif Bozunma'], badge: 'AYT Her Yıl', has_turkish: false, is_active: true },
  { slug: 'harmonik-hareket', phet_id: 'pendulum-lab', title_tr: 'Basit Sarkaç & Harmonik Hareket', description: 'Sarkaç uzunluğu, kütle ve yer çekimine göre periyot değişimi ve enerji dönüşümü.', category: 'AYT', subject: 'Fizik', topic: 'Harmonik Hareket', difficulty_level: 3, related_yks_topics: ['Basit Sarkaç', 'Periyot Formülü', 'SHM'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'yaylar-ve-kutleler', phet_id: 'masses-and-springs', title_tr: 'Yaylar & Kütleler', description: 'Yay sabiti, kütle ve yer çekimine göre frekans, periyot ve enerji hesabı.', category: 'AYT', subject: 'Fizik', topic: 'Harmonik Hareket', difficulty_level: 3, related_yks_topics: ['Yay Hareketi', 'Frekans', 'Potansiyel Enerji'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'surtunme', phet_id: 'friction', title_tr: 'Sürtünme Kuvveti', description: 'Statik ve kinetik sürtünme katsayısı, yüzey türü ve kütle değiştirerek sürtünme deneyi.', category: 'TYT', subject: 'Fizik', topic: 'Dinamik', difficulty_level: 2, related_yks_topics: ['Sürtünme Kuvveti', 'Normal Kuvvet', 'Katsayılar'], badge: 'TYT Fizik', has_turkish: true, is_active: true },
  { slug: 'optik', phet_id: 'geometric-optics', title_tr: 'Geometrik Optik', description: 'İnce mercekler, odak uzaklığı, görüntü oluşumu ve mercek-gözlem denklemi deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Optik', difficulty_level: 3, related_yks_topics: ['İnce Mercekler', 'Odak Uzaklığı', 'Ayna Formülü'], badge: 'AYT Optik', has_turkish: true, is_active: true },
  { slug: 'piller', phet_id: 'circuit-construction-kit-ac', title_tr: 'Piller & Alternatif Akım Devreleri', description: 'AC ve DC devrelerde direnç, kondansatör ve bobin ile empedans ve güç analizi.', category: 'AYT', subject: 'Fizik', topic: 'Alternatif Akım', difficulty_level: 4, related_yks_topics: ['AC Devreleri', 'Empedans', 'Güç Faktörü'], badge: 'AYT Elektrik', has_turkish: false, is_active: true },
  { slug: 'transformatorler', phet_id: 'faradays-electromagnetic-lab', title_tr: 'Transformatörler & Alternatif Akım', description: 'Primer/sekonder sarım oranı, gerilim yükseltme/düşürme, güç korumu ve yük lambası parlaklığı deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Alternatif Akım & İndüksiyon', difficulty_level: 4, related_yks_topics: ['Transformatörler', 'İndüksiyon Gerilimi', 'Alternatif Akım', 'Verim'], badge: 'AYT Banko Soru', has_turkish: false, is_active: true },
  { slug: 'kepler', phet_id: 'my-solar-system', title_tr: 'Kepler Yasaları & Gezegen Hareketleri', description: 'Güneş sistemi simülasyonu, eliptik yörüngeler, periyot-yarı eksen ilişkisi ve çekim kuvveti.', category: 'AYT', subject: 'Fizik', topic: 'Evrensel Çekim', difficulty_level: 4, related_yks_topics: ['Kepler Yasaları', 'Eliptik Yörüngeler', 'Evrensel Çekim'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'vektorler', phet_id: 'vector-addition', title_tr: 'Vektör Toplama & Bileşen Analizi', description: 'Grafik ve bileşen yöntemiyle vektör toplama, vektör ayrıştırma ve iç çarpım.', category: 'AYT', subject: 'Fizik', topic: 'Vektörler', difficulty_level: 2, related_yks_topics: ['Vektör Toplama', 'Bileşenler', 'İç Çarpım'], badge: 'AYT Temel', has_turkish: true, is_active: true },
  { slug: 'denge-oyunu', phet_id: 'balancing-act', title_tr: 'Denge & Tork Analizi', description: 'Kaldıraç kolları, tork, moment dengesi ve ağırlık merkezi deneyleri.', category: 'AYT', subject: 'Fizik', topic: 'Denge & Statik', difficulty_level: 3, related_yks_topics: ['Tork', 'Kaldıraç', 'Moment Dengesi'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'kati-cisimler', phet_id: 'density', title_tr: 'Yoğunluk & Yüzdürme Kuvveti', description: 'Maddenin yoğunluğu, hacim ölçme ve Arşimet prensibini interaktif deney ile öğren.', category: 'TYT', subject: 'Fizik', topic: 'Madde & Yoğunluk', difficulty_level: 2, related_yks_topics: ['Yoğunluk', 'Arşimet Prensibi', 'Batma/Yüzme'], badge: 'TYT Fizik', has_turkish: true, is_active: true },
  { slug: 'renk-gorme', phet_id: 'color-vision', title_tr: 'Renk Görme & Işık Spektrumu', description: 'RGB renk modeli, beyaz ışığın dağılması ve göz konisi pigmentleri ile renk algısı.', category: 'AYT', subject: 'Fizik', topic: 'Optik', difficulty_level: 2, related_yks_topics: ['Işık Spektrumu', 'RGB Modeli', 'Renk Algısı'], badge: 'AYT Optik', has_turkish: false, is_active: true },
  { slug: 'basit-makineler', phet_id: 'balancing-act', title_tr: 'Basit Makineler: Makara & Palangalar', description: 'Sabit makara, hareketli makara ve palangalarda kuvvet kazancı, yoldan kayıp ve sistem verimi.', category: 'TYT', subject: 'Fizik', topic: 'Basit Makineler', difficulty_level: 3, related_yks_topics: ['Sabit Makara', 'Hareketli Makara', 'Palangalar', 'Verim'], badge: 'TYT/AYT', has_turkish: true, is_active: true },

  // ─── KİMYA (38 simülasyon) ────────────────────────────────────────────────
  { slug: 'ideal-gaz', phet_id: 'gas-properties', title_tr: 'İdeal Gaz Kanunları', description: 'P, V, T değişkenlerini değiştirerek Boyle, Charles ve Gay-Lussac Yasaları deneyi.', category: 'TYT', subject: 'Kimya', topic: 'Gazlar', difficulty_level: 2, related_yks_topics: ['İdeal Gaz', 'Boyle Yasası', 'Charles Yasası', 'Gay-Lussac'], badge: 'TYT/AYT Banko', has_turkish: true, is_active: true },
  { slug: 'maddenin-halleri', phet_id: 'states-of-matter', title_tr: 'Maddenin Halleri & Faz Değişimi', description: 'Moleküler seviyede katı-sıvı-gaz geçişleri, ısıtma/soğutma eğrileri ve ara yüzey.', category: 'TYT', subject: 'Kimya', topic: 'Maddenin Halleri', difficulty_level: 2, related_yks_topics: ['Faz Değişimi', 'Erime-Donma', 'Buharlaşma-Yoğunlaşma'], badge: 'TYT Kimya', has_turkish: true, is_active: true },
  { slug: 'le-chatelier', phet_id: 'reactions-and-rates', title_tr: 'Le Chatelier Prensibi', description: 'Kimyasal denge, konsantrasyon/basınç/sıcaklık değişimine tepki ve K hesabı.', category: 'AYT', subject: 'Kimya', topic: 'Kimyasal Denge', difficulty_level: 4, related_yks_topics: ['Le Chatelier', 'Denge Sabiti', 'Ters Tepkime'], badge: 'AYT Her Yıl', has_turkish: false, is_active: true },
  { slug: 'titrasyon', phet_id: 'acid-base-solutions', title_tr: 'Asit-Baz Titrasyonu', description: 'pH metre, titrasyon eğrisi, eşdeğerlik noktası ve tampon çözelti deneyi.', category: 'AYT', subject: 'Kimya', topic: 'Asitler & Bazlar', difficulty_level: 4, related_yks_topics: ['Titrasyon', 'pH Ölçümü', 'Tampon Çözelti'], badge: 'AYT Banko', has_turkish: true, is_active: true },
  { slug: 'elektrokimyasal-pil', phet_id: 'sugar-and-salt-solutions', title_tr: 'Galvanik Pil & Nernst Eşitliği', description: 'Zn-Cu Daniell pili, anot/katot derişim değişimi, tuz köprüsü iyon göçü ve Nernst potansiyel hesabı.', category: 'AYT', subject: 'Kimya', topic: 'Elektrokimya & Piller', difficulty_level: 4, related_yks_topics: ['Galvanik Piller', 'Nernst Eşitliği', 'Anot ve Katot', 'Tuz Köprüsü'], badge: 'Her Yıl 1 Soru', has_turkish: false, is_active: true },
  { slug: 'molekul-sekilleri', phet_id: 'molecule-shapes', title_tr: 'Molekül Geometrisi (VSEPR)', description: 'Lewis yapısı, bağ çifti, yalnız çift elektron ve VSEPR teorisiyle 3D molekül şekilleri.', category: 'AYT', subject: 'Kimya', topic: 'Kimyasal Bağlar', difficulty_level: 3, related_yks_topics: ['VSEPR Teorisi', 'Molekül Geometrisi', 'Lewis Yapısı'], badge: 'AYT Kimya', has_turkish: true, is_active: true },
  { slug: 'graham-difuzyon', phet_id: 'diffusion', title_tr: 'Graham Gaz Difüzyon Yasası', description: 'Cam boru içinde farklı sıcaklık ve mol kütleli iki gazın difüzyon hızı ve karşılaşma noktası.', category: 'AYT', subject: 'Kimya', topic: 'Gazlar', difficulty_level: 3, related_yks_topics: ['Gazlarda Difüzyon', 'Graham Yasası', 'Kinetik Teori'], badge: 'AYT Klasik Soru', has_turkish: false, is_active: true },
  { slug: 'kcc-cokelme', phet_id: 'soluble-salts', title_tr: 'Ksp & Çökelme Dengesi', description: 'Çözünürlük çarpımı, iyon çarpımı ve çökelme koşullarını interaktif deney.', category: 'AYT', subject: 'Kimya', topic: 'Çözünürlük Dengesi', difficulty_level: 4, related_yks_topics: ['Ksp', 'Çökelme', 'Çözünürlük'], badge: 'AYT Her Yıl', has_turkish: false, is_active: true },
  { slug: 'engelmann-deneyi', phet_id: 'blackbody-spectrum', title_tr: 'Işık Absorbsiyon Spektrumu', description: 'Spektroskopi ve ışık absorbsiyonu ile element tanıma deneyi.', category: 'AYT', subject: 'Kimya', topic: 'Spektroskopi', difficulty_level: 3, related_yks_topics: ['Absorbsiyon Spektrumu', 'Element Tanıma', 'Spektroskopi'], badge: 'AYT Kimya', has_turkish: false, is_active: true },

  // ─── BİYOLOJİ (25 simülasyon) ────────────────────────────────────────────
  { slug: 'dogal-secilim', phet_id: 'natural-selection', title_tr: 'Doğal Seçilim & Evrim', description: 'Adaptasyon, doğal seçilim ve popülasyon genetiği ile evrim sürecini simüle et.', category: 'TYT', subject: 'Biyoloji', topic: 'Evrim', difficulty_level: 2, related_yks_topics: ['Doğal Seçilim', 'Adaptasyon', 'Evrim'], badge: 'TYT Biyoloji', has_turkish: true, is_active: true },
  { slug: 'punnett', phet_id: 'gene-expression-essentials', title_tr: 'Kalıtım & Punnett Karesi', description: 'Tek ve çift gen melezlemesi, dominantlık, geri melez ve Punnett karesi analizi.', category: 'TYT', subject: 'Biyoloji', topic: 'Kalıtım', difficulty_level: 3, related_yks_topics: ['Punnett Karesi', 'Mendel Yasaları', 'Dominantlık'], badge: 'TYT/AYT Banko', has_turkish: false, is_active: true },
  { slug: 'hucre-zari', phet_id: 'membrane-channels', title_tr: 'Hücre Zarı & Osmoz', description: 'Fosfolipid çift tabaka, osmoz, difüzyon ve aktif taşıma mekanizmaları deneyi.', category: 'TYT', subject: 'Biyoloji', topic: 'Hücre', difficulty_level: 2, related_yks_topics: ['Hücre Zarı', 'Osmoz', 'Aktif Taşıma'], badge: 'TYT Biyoloji', has_turkish: false, is_active: true },
  { slug: 'fotosentez', phet_id: 'sugar-and-salt-solutions', title_tr: 'Fotosentez & Kemosentez', description: 'Işık şiddeti, CO₂ konsantrasyonu ve sıcaklığa göre fotosentez hızı değişimi.', category: 'TYT', subject: 'Biyoloji', topic: 'Metabolizma', difficulty_level: 3, related_yks_topics: ['Fotosentez', 'Kemosentez', 'Klorofil'], badge: 'TYT Biyoloji', has_turkish: false, is_active: true },
  { slug: 'enzim-kinetigi', phet_id: 'reactants-products-and-leftovers', title_tr: 'Enzim Kinetiği & Michaelis-Menten', description: 'Substrat konsantrasyonu, enzim inhibisyonu ve pH bağımlılığı ile enzim aktivitesi deneyi.', category: 'AYT', subject: 'Biyoloji', topic: 'Enzimler', difficulty_level: 4, related_yks_topics: ['Enzim Kinetiği', 'İnhibisyon', 'Michaelis Sabiti'], badge: 'AYT Biyoloji', has_turkish: false, is_active: true },
  { slug: 'mayoz-bolunme', phet_id: 'meiosis', title_tr: 'Mayoz Bölünme & Krossing-over', description: 'Tetrat, sinapsis, krossing-over varyasyonu, homolog ve kardeş kromatit ayrılması.', category: 'TYT', subject: 'Biyoloji', topic: 'Hücre Bölünmeleri', difficulty_level: 3, related_yks_topics: ['Mayoz Bölünme', 'Krossing-over', 'Gamet Oluşumu'], badge: 'TYT Banko Soru', has_turkish: false, is_active: true },

  // ─── MATEMATİK (40 simülasyon) ────────────────────────────────────────────
  { slug: 'kesirler', phet_id: 'fractions-intro', title_tr: 'Kesirler & Oran Analizi', description: 'Kesir modelleri, eşdeğer kesirler, toplama-çıkarma ve oran kavramı.', category: 'TYT', subject: 'Matematik', topic: 'Sayı Sistemleri', difficulty_level: 1, related_yks_topics: ['Kesirler', 'Oranlar', 'Kesirlerde İşlemler'], badge: 'TYT Matematik', has_turkish: false, is_active: true },
  { slug: 'limit', phet_id: 'graphing-lines', title_tr: 'Limit & Süreklilik', description: 'Fonksiyon grafikleri, tek taraflı limitler ve süreksizlik noktaları görselleştirmesi.', category: 'AYT', subject: 'Matematik', topic: 'Analiz', difficulty_level: 4, related_yks_topics: ['Limit', 'Süreklilik', 'Asimptot'], badge: 'AYT Analiz', has_turkish: false, is_active: true },
  { slug: 'turev', phet_id: 'calculus-grapher', title_tr: 'Türev & Diferansiyel Hesap', description: 'Fonksiyon grafiği, türev grafiği ve integral altındaki alan interaktif görselleştirmesi.', category: 'AYT', subject: 'Matematik', topic: 'Analiz', difficulty_level: 4, related_yks_topics: ['Türev Kuralları', 'Monotonluk', 'Ekstremum'], badge: 'AYT Analiz', has_turkish: false, is_active: true },
  { slug: 'riemann', phet_id: 'calculus-grapher', title_tr: 'Riemann Toplamı & İntegral', description: 'Belirli integral, Riemann toplamı ve alan hesabı ile analitik integral karşılaştırması.', category: 'AYT', subject: 'Matematik', topic: 'Analiz', difficulty_level: 4, related_yks_topics: ['Belirli İntegral', 'Riemann Toplamı', 'Alan Hesabı'], badge: 'AYT Analiz', has_turkish: false, is_active: true },
  { slug: 'polinom', phet_id: 'graphing-quadratics', title_tr: 'Polinom Fonksiyonları & Kökler', description: 'Quadratic, cubic ve higher-degree polinomların grafiksel davranışı ve kökleri.', category: 'AYT', subject: 'Matematik', topic: 'Fonksiyonlar', difficulty_level: 3, related_yks_topics: ['Polinom Fonksiyonlar', 'Köklerin Bulunması', 'Grafik Analizi'], badge: 'AYT Matematik', has_turkish: true, is_active: true },
  { slug: 'matematik-grafikleri', phet_id: 'graphing-lines', title_tr: 'Doğrusal Fonksiyon & Grafik', description: 'Eğim, y-kesişim, iki noktalı doğru ve paralel/dik doğru ilişkisi.', category: 'TYT', subject: 'Matematik', topic: 'Fonksiyonlar', difficulty_level: 2, related_yks_topics: ['Doğrusal Fonksiyon', 'Eğim', 'Doğru Denklemi'], badge: 'TYT Matematik', has_turkish: false, is_active: true },
  { slug: 'birim-cember', phet_id: 'trig-tour', title_tr: 'Birim Çember & Trigonometri', description: 'Birim çember üzerinde açılar, sin/cos/tan değerleri ve trigonometrik özdeşlikler.', category: 'AYT', subject: 'Matematik', topic: 'Trigonometri', difficulty_level: 3, related_yks_topics: ['Birim Çember', 'Trigonometrik Fonksiyonlar', 'Radyan'], badge: 'AYT Trigonometri', has_turkish: false, is_active: true },
  { slug: 'galton', phet_id: 'plinko-probability', title_tr: 'Galton Tahtası & Olasılık', description: 'Binom dağılımı, normal dağılım yaklaşımı ve olasılıksal simülasyon.', category: 'TYT', subject: 'Matematik', topic: 'Olasılık & İstatistik', difficulty_level: 3, related_yks_topics: ['Olasılık', 'Binom Dağılımı', 'Normal Dağılım'], badge: 'TYT Olasılık', has_turkish: false, is_active: true },
  { slug: 'alan-olusturucu', phet_id: 'area-builder', title_tr: 'Alan Oluşturucu & Geometrik Çevre', description: 'Birim kareler ve çokgenlerle alan-çevre ilişkisi, alan korunumlu şekil deformasyonları.', category: 'TYT', subject: 'Matematik', topic: 'Geometri', difficulty_level: 2, related_yks_topics: ['Alan ve Çevre', 'Çokgenler', 'Birim Kareler'], badge: 'TYT Geometri', has_turkish: false, is_active: true },
  { slug: 'izohips-haritasi', phet_id: 'graphing-slope-intercept', title_tr: 'İzohips Haritası & Kesit Profili', description: 'Eş yükselti eğrileri, tepe, sırt, vadi, falez ve kapalı çukur şekilleri ile dinamik A-B profil kesiti çıkarma.', category: 'TYT', subject: 'Matematik', topic: 'Harita Bilgisi & Topoğrafya', difficulty_level: 3, related_yks_topics: ['İzohips Eğrileri', 'Profil Çıkarma', 'Eğim Hesabı', 'Yer Şekilleri'], badge: 'TYT Banko Soru', has_turkish: false, is_active: true },

  // ─── YENİ SİMÜLASYONLAR (FAZ 2 - 80+ Yeni) ──────────────────────────────
  // FİZİK YENİ
  { slug: 'ohm-kanunu', phet_id: 'ohms-law', title_tr: 'Ohm Kanunu', description: 'Voltaj, direnç ve akım üçgeni ile Ohm Yasasını interaktif grafik üzerinde öğren.', category: 'TYT', subject: 'Fizik', topic: 'Elektrik Devreleri', difficulty_level: 1, related_yks_topics: ['Ohm Yasası', 'Voltaj', 'Akım', 'Direnç'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'faraday-kanunu', phet_id: 'faradays-law', title_tr: 'Faraday Kanunu - EMK', description: 'Bobine yaklaştırılan mıknatısla endüktif EMK, akımın yönü ve Lenz yasasını gözlemle.', category: 'AYT', subject: 'Fizik', topic: 'Elektromanyetik İndüksiyon', difficulty_level: 4, related_yks_topics: ['Faraday Kanunu', 'EMK', 'Lenz Yasası', 'İndüksiyon'], badge: 'AYT Banko', has_turkish: true, is_active: true },
  { slug: 'elektrik-alani', phet_id: 'charges-and-fields', title_tr: 'Elektrik Alanı & Yük Dağılımı', description: 'Nokta yüklerin oluşturduğu elektrik alanı, alan çizgileri ve potansiyel yüzeyleri.', category: 'AYT', subject: 'Fizik', topic: 'Elektrostatik', difficulty_level: 4, related_yks_topics: ['Elektrik Alan', 'Coulomb Kuvveti', 'Elektrik Potansiyeli'], badge: 'AYT Elektrik', has_turkish: true, is_active: true },
  { slug: 'coulomb-kuvveti', phet_id: 'coulombs-law', title_tr: 'Coulomb Kuvveti', description: 'İki yüklü cisim arasındaki elektrik kuvvetini mesafe ve yük büyüklüğüne göre incele.', category: 'AYT', subject: 'Fizik', topic: 'Elektrostatik', difficulty_level: 3, related_yks_topics: ['Coulomb Yasası', 'Elektrik Kuvveti', 'Yük'], badge: 'AYT Elektrik', has_turkish: true, is_active: true },
  { slug: 'newton-cekimi', phet_id: 'gravity-force-lab', title_tr: 'Newton Evrensel Çekim', description: 'İki kütle arasındaki çekim kuvvetini kütle ve mesafeye göre değiştirerek gözlemle.', category: 'AYT', subject: 'Fizik', topic: 'Evrensel Çekim', difficulty_level: 3, related_yks_topics: ['Evrensel Çekim', 'Newton Yasası', 'Gravitasyon'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'enerji-bicim-degisim', phet_id: 'energy-forms-and-changes', title_tr: 'Enerji Biçim Değişimleri', description: 'Isı, elektrik, mekanik ve kimyasal enerji arasındaki dönüşümleri interaktif keşfet.', category: 'TYT', subject: 'Fizik', topic: 'Enerji', difficulty_level: 2, related_yks_topics: ['Enerji Dönüşümü', 'Isı Enerjisi', 'Kimyasal Enerji'], badge: 'TYT Fizik', has_turkish: true, is_active: true },
  { slug: 'basinc-akiskan', phet_id: 'under-pressure', title_tr: 'Basınç & Akışkan Mekaniği', description: 'Sıvı basıncı, derinlik, Bernoulli ilkesi ve akışkan hızı ilişkisini keşfet.', category: 'AYT', subject: 'Fizik', topic: 'Akışkanlar', difficulty_level: 3, related_yks_topics: ['Sıvı Basıncı', 'Bernoulli', 'Akışkan Mekaniği'], badge: 'AYT Fizik', has_turkish: true, is_active: true },
  { slug: 'ses-dalgalari', phet_id: 'sound', title_tr: 'Ses Dalgaları & Frekans', description: 'Frekans, genlik, ses hızı ve ortam değişimiyle ses dalgalarını görsel incele.', category: 'TYT', subject: 'Fizik', topic: 'Dalgalar', difficulty_level: 2, related_yks_topics: ['Ses Dalgaları', 'Frekans', 'Desibel'], badge: 'TYT Fizik', has_turkish: true, is_active: true },
  { slug: 'dalga-girisim', phet_id: 'wave-interference', title_tr: 'Dalga Girişimi & Kırınım', description: 'İki kaynaklı girişim deseni, kırınım ve Huygens prensibi deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Dalgalar', difficulty_level: 4, related_yks_topics: ['Dalga Girişimi', 'Kırınım', 'Huygens Prensibi'], badge: 'AYT Optik', has_turkish: true, is_active: true },
  { slug: 'biot-savart', phet_id: 'magnets-and-electromagnets', title_tr: 'Manyetik Alan & Elektromanyetizma', description: 'Düz tel ve bobin etrafındaki manyetik alan çizgileri ile elektromıknatıs deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Manyetizma', difficulty_level: 4, related_yks_topics: ['Manyetik Alan', 'Biot-Savart', 'Elektromıknatıs'], badge: 'AYT Elektrik', has_turkish: false, is_active: true },
  { slug: 'kinetik-kuram', phet_id: 'gas-properties', title_tr: 'Kinetik Gaz Kuramı', description: 'Gaz moleküllerinin hız dağılımı, ortalama kinetik enerji ve sıcaklık ilişkisi.', category: 'AYT', subject: 'Fizik', topic: 'Isı & Termodinamik', difficulty_level: 3, related_yks_topics: ['Kinetik Kuram', 'Maxwell Dağılımı', 'Ortalama Kinetik Enerji'], badge: 'AYT Fizik', has_turkish: true, is_active: true },
  { slug: 'is-guc-enerji', phet_id: 'energy-skate-park-basics', title_tr: 'İş, Güç & Enerji Analizi', description: 'Kuvvet-yer değiştirme grafiği, iş hesabı ve güç-zaman ilişkisi deneyi.', category: 'TYT', subject: 'Fizik', topic: 'Enerji', difficulty_level: 2, related_yks_topics: ['İş Hesabı', 'Güç', 'Verim'], badge: 'TYT Fizik', has_turkish: false, is_active: true },

  // KİMYA YENİ
  { slug: 'periyodik-tablo', phet_id: 'build-an-atom', title_tr: 'Periyodik Sistem & Elektron Dizilimi', description: 'Periyodik tablo, atom numarası, elektron konfigürasyonu ve periyodik özellikler.', category: 'TYT', subject: 'Kimya', topic: 'Periyodik Sistem', difficulty_level: 2, related_yks_topics: ['Periyodik Tablo', 'Elektron Dizilimi', 'Periyodik Özellikler'], badge: 'TYT/AYT Kimya', has_turkish: true, is_active: true },
  { slug: 'kimyasal-tepkime', phet_id: 'reactants-products-and-leftovers', title_tr: 'Kimyasal Tepkime & Stokiyometri', description: 'Mol hesabı, sınırlayan reaktif ve stokiyometrik hesapları interaktif deney.', category: 'AYT', subject: 'Kimya', topic: 'Stokiyometri', difficulty_level: 3, related_yks_topics: ['Mol Hesabı', 'Sınırlayan Reaktif', 'Stokiyometri'], badge: 'AYT Kimya', has_turkish: false, is_active: true },
  { slug: 'cozunurluk-denge', phet_id: 'soluble-salts', title_tr: 'Çözünürlük & Denge', description: 'İyon çarpımı, ortak iyon etkisi ve çözünürlük denge hesapları.', category: 'AYT', subject: 'Kimya', topic: 'Çözünürlük Dengesi', difficulty_level: 4, related_yks_topics: ['Ksp', 'Ortak İyon Etkisi', 'Çözünürlük'], badge: 'AYT Kimya', has_turkish: false, is_active: false },
  { slug: 'asit-baz-ph', phet_id: 'ph-scale', title_tr: 'Asit-Baz & pH Skalası', description: 'pH ve pOH ölçümleri, asit/baz kuvveti ve günlük hayattaki çözeltilerin pH değerleri.', category: 'TYT', subject: 'Kimya', topic: 'Asitler & Bazlar', difficulty_level: 2, related_yks_topics: ['pH Skalası', 'Kuvvetli Asit-Baz', 'Zayıf Asit-Baz'], badge: 'TYT/AYT Kimya', has_turkish: true, is_active: true },
  { slug: 'mol-miktari', phet_id: 'concentration', title_tr: 'Derişim & Mol Hesabı', description: 'Çözünen mol miktarı, hacim ve derişim ilişkisi ile Beer-Lambert deneyimi.', category: 'AYT', subject: 'Kimya', topic: 'Çözeltiler', difficulty_level: 3, related_yks_topics: ['Derişim Hesabı', 'Mol', 'Beer-Lambert'], badge: 'AYT Kimya', has_turkish: true, is_active: true },
  { slug: 'elektroliz', phet_id: 'sugar-and-salt-solutions', title_tr: 'Elektroliz & Elektrokimya', description: 'Elektroliz hücresi, elektrot tepkimeleri ve Faraday yasası ile metalin kaplanması.', category: 'AYT', subject: 'Kimya', topic: 'Elektrokimya', difficulty_level: 4, related_yks_topics: ['Elektroliz', 'Faraday Yasası', 'Elektrot Tepkimeleri'], badge: 'AYT Kimya', has_turkish: false, is_active: false },
  { slug: 'organik-kimya', phet_id: 'molecule-shapes', title_tr: 'Organik Moleküller & Bağ Açıları', description: 'Organik bileşiklerde sp, sp2, sp3 hibritleşme ve 3D yapı.', category: 'AYT', subject: 'Kimya', topic: 'Organik Kimya', difficulty_level: 4, related_yks_topics: ['Hibritleşme', 'Organik Bağlar', 'VSEPR'], badge: 'AYT Organik', has_turkish: true, is_active: true },
  { slug: 'reaksiyon-hizi', phet_id: 'reactions-and-rates', title_tr: 'Reaksiyon Hızı & Aktivasyon Enerjisi', description: 'Sıcaklık, katalizör ve konsantrasyon değişiminin reaksiyon hızına etkisi.', category: 'AYT', subject: 'Kimya', topic: 'Reaksiyon Hızı', difficulty_level: 4, related_yks_topics: ['Reaksiyon Hızı', 'Aktivasyon Enerjisi', 'Katalizör'], badge: 'AYT Kimya', has_turkish: false, is_active: true },

  // BİYOLOJİ YENİ
  { slug: 'gen-ekspresyonu', phet_id: 'gene-expression-essentials', title_tr: 'Gen Ekspresyonu (Transkripsiyon & Translasyon)', description: 'DNA→mRNA transkripsiyon, kodon-antikodon eşleşmesi ve protein sentezi deneyi.', category: 'AYT', subject: 'Biyoloji', topic: 'Genetik & Moleküler Biyoloji', difficulty_level: 4, related_yks_topics: ['Transkripsiyon', 'Translasyon', 'Protein Sentezi'], badge: 'AYT Biyoloji', has_turkish: false, is_active: true },
  { slug: 'mendel-genetigi', phet_id: 'gene-expression-essentials', title_tr: 'Mendel Genetiği & Kalıtım', description: 'Mono ve dihybrid melezlemeler, F1-F2 nesilleri ve Hardy-Weinberg dengesi.', category: 'TYT', subject: 'Biyoloji', topic: 'Kalıtım', difficulty_level: 3, related_yks_topics: ['Mendel Yasaları', 'Dihybrid Melezleme', 'Hardy-Weinberg'], badge: 'TYT Biyoloji', has_turkish: false, is_active: false },
  { slug: 'ekoloji-populasyon', phet_id: 'natural-selection', title_tr: 'Ekoloji & Popülasyon Dinamiği', description: 'Besin ağı, av-yırtıcı ilişkisi, taşıma kapasitesi ve popülasyon büyüme modelleri.', category: 'TYT', subject: 'Biyoloji', topic: 'Ekoloji', difficulty_level: 2, related_yks_topics: ['Besin Ağı', 'Popülasyon Dinamiği', 'Taşıma Kapasitesi'], badge: 'TYT Biyoloji', has_turkish: true, is_active: true },

  // MATEMATİK YENİ
  { slug: 'olasilik-hesabi', phet_id: 'plinko-probability', title_tr: 'Olasılık & İstatistik Temelleri', description: 'Binom dağılımı, Monte Carlo simülasyonu ve temel istatistik hesaplamaları.', category: 'TYT', subject: 'Matematik', topic: 'Olasılık & İstatistik', difficulty_level: 2, related_yks_topics: ['Permütasyon', 'Kombinasyon', 'Olasılık'], badge: 'TYT Matematik', has_turkish: false, is_active: true },
  { slug: 'integral-alan', phet_id: 'calculus-grapher', title_tr: 'İntegral & Alan Hesabı', description: 'Belirli integralin geometrik yorumu, pozitif/negatif alan ve iki fonksiyon arası alan.', category: 'AYT', subject: 'Matematik', topic: 'Analiz', difficulty_level: 4, related_yks_topics: ['Belirli İntegral', 'Alan Hesabı', 'Newton-Leibniz'], badge: 'AYT Analiz', has_turkish: false, is_active: true },
  { slug: 'matris-vektorler', phet_id: 'vector-addition', title_tr: 'Matris & Vektör Dönüşümleri', description: 'Lineer dönüşümler, özvektörler ve matris çarpımının geometrik yorumu.', category: 'AYT', subject: 'Matematik', topic: 'Matrisler', difficulty_level: 5, related_yks_topics: ['Matris', 'Determinant', 'Lineer Dönüşüm'], badge: 'AYT Matematik', has_turkish: false, is_active: true },
  { slug: 'trigonometri-grafik', phet_id: 'trig-tour', title_tr: 'Trigonometrik Fonksiyon Grafikleri', description: 'sin, cos, tan fonksiyonlarının periyot, genlik, faz kayması parametreleri.', category: 'AYT', subject: 'Matematik', topic: 'Trigonometri', difficulty_level: 3, related_yks_topics: ['Trigonometrik Fonksiyonlar', 'Periyot', 'Genlik'], badge: 'AYT Trigonometri', has_turkish: false, is_active: true },
  { slug: 'karmasik-sayilar', phet_id: 'graphing-quadratics', title_tr: 'Karmaşık Sayılar & Kompleks Düzlem', description: 'Karmaşık sayıların geometrik gösterimi, modül-argument ve dönüşümler.', category: 'AYT', subject: 'Matematik', topic: 'Sayı Sistemleri', difficulty_level: 4, related_yks_topics: ['Karmaşık Sayılar', 'Argand Düzlemi', 'Modül'], badge: 'AYT Matematik', has_turkish: false, is_active: false },
  { slug: 'logaritma', phet_id: 'graphing-lines', title_tr: 'Logaritma & Üstel Fonksiyonlar', description: 'Logaritma özellikleri, logaritmik ve üstel fonksiyon grafikleri ve denkleme uygulamaları.', category: 'AYT', subject: 'Matematik', topic: 'Fonksiyonlar', difficulty_level: 3, related_yks_topics: ['Logaritma', 'Üstel Fonksiyon', 'Değişim Oranı'], badge: 'AYT Matematik', has_turkish: false, is_active: true },

  // ─── FİZİK LİSE MÜFREDAT TAMAMLAYICILAR (ÖSYM Odaklı) ──────────────────────────
  { slug: 'hooke-yasasi', phet_id: 'hookes-law', title_tr: 'Hooke Yasası & Yay Sabiti', description: 'Yaylara uygulanan kuvvet, uzama miktarı, yay sabiti (k) ve seri/paralel bağlı yayların eşdeğer sabiti deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Kuvvet ve Hareket', difficulty_level: 2, related_yks_topics: ['Hooke Yasası', 'Yay Sabiti', 'Esneklik Potansiyel Enerjisi'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'kaldirma-kuvveti-arsimet', phet_id: 'buoyancy', title_tr: 'Sıvıların Kaldırma Kuvveti & Arşimet', description: 'Batan ve yüzen cisimler, taşan sıvı hacmi, özkütle ilişkisi ve dinamometre ile kaldırma kuvveti ölçümü.', category: 'TYT', subject: 'Fizik', topic: 'Madde ve Özellikleri', difficulty_level: 2, related_yks_topics: ['Kaldırma Kuvveti', 'Arşimet Prensibi', 'Yüzme Şartı', 'Askıda Kalma'], badge: 'TYT Banko', has_turkish: true, is_active: true },
  { slug: 'statik-elektrik-balonlar', phet_id: 'balloons-and-static-electricity', title_tr: 'Statik Elektrik & Yük Etkileşimi', description: 'Sürtünmeyle elektriklenme, pozitif ve negatif yük dağılımı, nötr cisimlerin kutuplanması ve çekme etkisi.', category: 'TYT', subject: 'Fizik', topic: 'Elektrostatik', difficulty_level: 1, related_yks_topics: ['Elektrostatik', 'Sürtünmeyle Elektriklenme', 'Elektriksel Yükler'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'direnc-iletken-tel', phet_id: 'resistance-in-a-wire', title_tr: 'İletkende Direnç (R = ρ·L/A)', description: 'İletken telin boyu (L), kesit alanı (A) ve özdirenci (ρ) değiştikçe elektriksel direncin değişimi.', category: 'TYT', subject: 'Fizik', topic: 'Elektrik Akımı', difficulty_level: 2, related_yks_topics: ['Özdirenç', 'İletken Direnci', 'Ohm Yasası'], badge: 'TYT/AYT', has_turkish: true, is_active: true },
  { slug: 'dalgalara-giris', phet_id: 'waves-intro', title_tr: 'Dalgalara Giriş (Su, Ses, Işık)', description: 'Farklı ortamlarda dalga üretimi, dalga boyu, genlik, frekans ve dalga hızının tepe-çukur ilişkisi.', category: 'TYT', subject: 'Fizik', topic: 'Dalgalar', difficulty_level: 2, related_yks_topics: ['Dalga Boyu', 'Frekans', 'Genlik', 'Dalga Hızı'], badge: 'TYT Dalgalar', has_turkish: true, is_active: true },
  { slug: 'kutlecekim-yorungeler', phet_id: 'gravity-and-orbits', title_tr: 'Kütleçekim ve Gezegen Yörüngeleri', description: 'Güneş, Dünya ve Ay yerçekimi etkileşimi, yerçekimsel sapan etkisi, eliptik ve dairesel yörünge mekaniği.', category: 'AYT', subject: 'Fizik', topic: 'Çembersel Hareket & Gravitasyon', difficulty_level: 3, related_yks_topics: ['Kepler Yasaları', 'Kütleçekim Kuvveti', 'Dolanım Periyodu'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'rutherford-sacilmasi', phet_id: 'rutherford-scattering', title_tr: 'Rutherford Atom Modeli & Alfa Saçılması', description: 'Altın yaprağa alfa tanecikleri bombardımanı, çekirdek kavramının keşfi ve Coulomb saçılma açısı.', category: 'AYT', subject: 'Fizik', topic: 'Atom Fiziğine Giriş', difficulty_level: 3, related_yks_topics: ['Rutherford Atom Modeli', 'Alfa Saçılması', 'Çekirdek'], badge: 'AYT Modern Fizik', has_turkish: true, is_active: true },
  { slug: 'kara-cisim-isimasi', phet_id: 'blackbody-spectrum', title_tr: 'Kara Cisim Işıması & Wien Yasası', description: 'Sıcaklığa bağlı ışıma spektrumu, tepe dalga boyu kayması (Wien Yasası) ve foton enerjisi dağılımı.', category: 'AYT', subject: 'Fizik', topic: 'Modern Fizik', difficulty_level: 4, related_yks_topics: ['Kara Cisim Işıması', 'Wien Kayma Yasası', 'Foton Frekansı'], badge: 'AYT Modern Fizik', has_turkish: true, is_active: true },
  { slug: 'hidrojen-atom-modelleri', phet_id: 'models-of-the-hydrogen-atom', title_tr: 'Bohr Hidrojen Atom Modeli & Spektrum', description: 'Farklı atom modelleri (Dalton, Thomson, Rutherford, Bohr, De Broglie) ve hidrojen emisyon/absorpsiyon spektrumu.', category: 'AYT', subject: 'Fizik', topic: 'Atom Fiziğine Giriş', difficulty_level: 4, related_yks_topics: ['Bohr Atom Modeli', 'Enerji Seviyeleri', 'Lyman/Balmer Serisi'], badge: 'AYT Modern Fizik', has_turkish: false, is_active: true },
  { slug: 'nukleer-fisyon-zincirleme', phet_id: 'nuclear-fission', title_tr: 'Nükleer Fisyon & Zincirleme Reaksiyon', description: 'U-235 çekirdeğine nötron çarpmasıyla fisyon, açığa çıkan nötronlar ve nükleer reaktör kontrol çubukları.', category: 'AYT', subject: 'Fizik', topic: 'Radyoaktivite & Modern Fizik', difficulty_level: 4, related_yks_topics: ['Nükleer Fisyon', 'Zincirleme Tepkime', 'Kütle-Enerji Eşdeğerliği'], badge: 'AYT Modern Fizik', has_turkish: false, is_active: true },
  { slug: 'john-travoltage-statik', phet_id: 'john-travoltage', title_tr: 'Elektrostatik Yüklenme & Boşalma', description: 'Halıya sürtünmeyle elektron yüklenmesi ve kapı koluna dokunulduğunda deşarj (kıvılcım) olayı.', category: 'TYT', subject: 'Fizik', topic: 'Elektrostatik', difficulty_level: 1, related_yks_topics: ['Elektrostatik Boşalma', 'Yük Transferi', 'Topraklama'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'alternatif-akim-rlc', phet_id: 'circuit-construction-kit-ac', title_tr: 'Alternatif Akım (AC) & RLC Devresi', description: 'Direnç (R), bobin (L) ve kondansatör (C) bileşenli AC devreler, rezonans frekansı ve faz farkı.', category: 'AYT', subject: 'Fizik', topic: 'Alternatif Akım', difficulty_level: 4, related_yks_topics: ['Alternatif Akım', 'Endüktif Reaktans', 'Kapasitif Reaktans', 'Rezonans'], badge: 'AYT Banko', has_turkish: true, is_active: true },

  // ─── KİMYA LİSE MÜFREDAT TAMAMLAYICILAR (ÖSYM Odaklı) ──────────────────────────
  { slug: 'izotoplar-ve-atom-kutlesi', phet_id: 'isotopes-and-atomic-mass', title_tr: 'İzotoplar ve Ortalama Atom Kütlesi', description: 'İzotop atomlar, nötron sayısı farkı, doğada bulunma yüzdesi ve periyodik tablodaki ortalama atom kütlesi hesabı.', category: 'TYT', subject: 'Kimya', topic: 'Atom ve Periyodik Sistem', difficulty_level: 2, related_yks_topics: ['İzotop Atomlar', 'Bağıl Atom Kütlesi', 'Kütle Spektrometresi'], badge: 'TYT Banko', has_turkish: true, is_active: true },
  { slug: 'kimyasal-denklem-denklestirme', phet_id: 'balancing-chemical-equations', title_tr: 'Kimyasal Tepkime Denkleştirme', description: 'Kütlenin korunumu yasası gereği reaktif ve ürünlerdeki atom sayılarını katsayılarla eşitleme oyunu.', category: 'TYT', subject: 'Kimya', topic: 'Kimyasal Hesaplamalar', difficulty_level: 2, related_yks_topics: ['Kütlenin Korunumu', 'Tepkime Denkleştirme', 'Stokiyometri'], badge: 'TYT Kimya', has_turkish: true, is_active: true },
  { slug: 'molekul-olustur', phet_id: 'build-a-molecule', title_tr: 'Molekül Oluştur & Kimyasal Formüller', description: 'Atomları kovalent bağlarla birleştirerek basit ve çok atomlu bileşik moleküllerinin formüllerini türetme.', category: 'TYT', subject: 'Kimya', topic: 'Kimyasal Türler Arası Etkileşimler', difficulty_level: 2, related_yks_topics: ['Kovalent Bağ', 'Kimyasal Formüller', 'Lewis Gösterimi'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'molekul-polaritesi', phet_id: 'molecule-polarity', title_tr: 'Molekül Polaritesi & Dipol Moment', description: 'Bağ elektronlarının dağılımı, elektronegatiflik farkı, kalıcı dipol ve molekülün kutuplu/kutupsuz olması.', category: 'TYT', subject: 'Kimya', topic: 'Kimyasal Türler Arası Etkileşimler', difficulty_level: 3, related_yks_topics: ['Polar Kovalent Bağ', 'Dipol Moment', 'Apolar Moleküller'], badge: 'TYT/AYT Kimya', has_turkish: true, is_active: true },
  { slug: 'tersinir-tepkimeler-denge', phet_id: 'reversible-reactions', title_tr: 'Tersinir Tepkimeler & Kimyasal Denge', description: 'İleri ve geri tepkime hızlarının eşitlenmesi, denge konsantrasyonları ve dinamik denge kavramı.', category: 'AYT', subject: 'Kimya', topic: 'Kimyasal Tepkimelerde Denge', difficulty_level: 4, related_yks_topics: ['Kimyasal Denge', 'Denge Sabiti (Kc)', 'Dinamik Denge'], badge: 'AYT Kimya', has_turkish: false, is_active: true },
  { slug: 'tuzlar-ve-cozunurluk', phet_id: 'soluble-salts', title_tr: 'Tuzlar ve Çözünürlük Çarpımı (Kçç)', description: 'Az çözünen tuzların doygunluk dengesi, iyon çarpımı (Q), çökelti oluşumu ve ortak iyon etkisi.', category: 'AYT', subject: 'Kimya', topic: 'Çözünürlük Dengesi', difficulty_level: 4, related_yks_topics: ['Kçç', 'Çökelme Şartı', 'Ortak İyon Etkisi'], badge: 'AYT Banko', has_turkish: false, is_active: true },
  { slug: 'cozelti-molarite', phet_id: 'molarity', title_tr: 'Molarite & Çözelti Konsantrasyonu (M = n/V)', description: 'Çözünen mol sayısı ve çözelti hacmi değiştirilerek molarite hesaplaması ve renk yoğunluğu incelemesi.', category: 'AYT', subject: 'Kimya', topic: 'Sıvı Çözeltiler ve Koligatif Özellikler', difficulty_level: 2, related_yks_topics: ['Molarite', 'Çözelti Derişimi', 'Seyreltme/Deriştirme'], badge: 'AYT Kimya', has_turkish: true, is_active: true },
  { slug: 'beer-lambert-kanunu', phet_id: 'beer-lambert-law', title_tr: 'Beer-Lambert Kanunu & Işık Absorbansı', description: 'Çözeltiden geçen ışığın dalga boyu, tabaka kalınlığı ve konsantrasyona bağlı ışık geçirgenliği (absorbans).', category: 'AYT', subject: 'Kimya', topic: 'Sıvı Çözeltiler', difficulty_level: 3, related_yks_topics: ['Beer-Lambert Yasası', 'Absorbans', 'Spektrofotometri'], badge: 'AYT Kimya', has_turkish: true, is_active: true },
  { slug: 'seker-ve-tuz-cozeltileri', phet_id: 'sugar-and-salt-solutions', title_tr: 'İyonik & Moleküler Çözeltiler (İletkenlik)', description: 'Suda çözünen sofra tuzu (iyonlarına ayrışma) ve şekerin (moleküler) elektrik iletkenliği farkı.', category: 'TYT', subject: 'Kimya', topic: 'Karışımlar', difficulty_level: 2, related_yks_topics: ['Elektrolit Çözeltiler', 'İyonik Çözünme', 'Elektrik İletkenliği'], badge: 'TYT Kimya', has_turkish: true, is_active: true },

  // ─── BİYOLOJİ LİSE MÜFREDAT TAMAMLAYICILAR (ÖSYM Odaklı) ──────────────────────────
  { slug: 'noron-aksiyon-potansiyeli', phet_id: 'neuron', title_tr: 'Nöron ve Aksiyon Potansiyeli', description: 'Sinir hücresi zarında Na+/K+ voltaj kapılı kanalları, polarizasyon, depolarizasyon ve impuls iletimi.', category: 'AYT', subject: 'Biyoloji', topic: 'İnsan Fizyolojisi (Sinir Sistemi)', difficulty_level: 4, related_yks_topics: ['Aksiyon Potansiyeli', 'İmpuls İletimi', 'Na-K Pompası', 'Sinaps'], badge: 'AYT Banko Soru', has_turkish: false, is_active: true },
  { slug: 'hucre-zari-kanallari', phet_id: 'membrane-channels', title_tr: 'Hücre Zarı & İyon Kanalları', description: 'Hücre zarından madde geçişleri, sızdırma kanalları, kapılı kanallar ve kolaylaştırılmış difüzyon simülasyonu.', category: 'TYT', subject: 'Biyoloji', topic: 'Hücre ve Madde Geçişleri', difficulty_level: 3, related_yks_topics: ['Hücre Zarı', 'Madde Geçişleri', 'İyon Kanalları'], badge: 'TYT Biyoloji', has_turkish: false, is_active: true },

  // ─── MATEMATİK LİSE MÜFREDAT TAMAMLAYICILAR (ÖSYM Odaklı) ──────────────────────────
  { slug: 'alan-modeli-cebir', phet_id: 'area-model-algebra', title_tr: 'Alan Modeli ile Cebir & Çarpanlara Ayırma', description: 'İki terimli çarpımlar (a+b)(c+d), tam kare özdeşlikler ve çarpanlara ayırmanın geometrik alan modeli.', category: 'TYT', subject: 'Matematik', topic: 'Çarpanlara Ayırma & Özdeşlikler', difficulty_level: 2, related_yks_topics: ['Özdeşlikler', 'Çarpanlara Ayırma', 'Geometrik Model'], badge: 'TYT Matematik', has_turkish: true, is_active: true },
  { slug: 'egri-uydurma-regresyon', phet_id: 'curve-fitting', title_tr: 'Eğri Uydurma & Regresyon Analizi', description: 'Dağılım grafiğindeki veri noktalarına en uygun doğru ve parabol eğrisini uydurma ve korelasyon hesabı.', category: 'TYT', subject: 'Matematik', topic: 'İstatistik & Veri', difficulty_level: 3, related_yks_topics: ['Regresyon Doğrusu', 'Veri Analizi', 'Korelasyon'], badge: 'TYT Matematik', has_turkish: true, is_active: true },
  { slug: 'fonksiyon-makinesi', phet_id: 'function-builder', title_tr: 'Fonksiyon Makinesi & Kural Oluşturucu', description: 'Girdi-çıktı tabloları, fonksiyonel işlem kuralları, ters fonksiyon ve iki fonksiyonun bileşkesi.', category: 'TYT', subject: 'Matematik', topic: 'Fonksiyonlar', difficulty_level: 2, related_yks_topics: ['Fonksiyon Tanımı', 'Değer Kümesi', 'Bileşke Fonksiyon'], badge: 'TYT/AYT', has_turkish: true, is_active: true },
  { slug: 'oran-oranti-benzerlik', phet_id: 'proportion-playground', title_tr: 'Oran-Orantı & Şekillerde Benzerlik', description: 'Doğru ve ters orantı katsayıları, benzer üçgen ve çokgenlerde kenar ve alan oranı ilişkisi.', category: 'TYT', subject: 'Matematik', topic: 'Oran ve Orantı', difficulty_level: 2, related_yks_topics: ['Oran Orantı', 'Benzerlik Oranı', 'Ölçek'], badge: 'TYT Matematik', has_turkish: true, is_active: true },
  { slug: 'kesir-eslestirme', phet_id: 'fraction-matcher', title_tr: 'Kesir Eşleştirme & Ondalık Gösterim', description: 'Görsel kesir modelleri, denk kesirler ve rasyonel sayıların sayı doğrusunda konumlandırılması oyunu.', category: 'TYT', subject: 'Matematik', topic: 'Rasyonel Sayılar', difficulty_level: 1, related_yks_topics: ['Rasyonel Sayılar', 'Denk Kesirler', 'Sayı Doğrusu'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'alan-modeli-carpma', phet_id: 'area-model-multiplication', title_tr: 'Çok Basamaklı Çarpma & Alan Modeli', description: 'Sayıları basamak değerlerine ayırarak çarpma işlemini dikdörtgensel alan parçalarıyla modelleme.', category: 'TYT', subject: 'Matematik', topic: 'Temel Kavramlar', difficulty_level: 1, related_yks_topics: ['Basamak Değeri', 'Çarpma İşlemi', 'Alan Modeli'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'ikinci-dereceden-parabol', phet_id: 'graphing-quadratics', title_tr: 'İkinci Dereceden Fonksiyonlar (Parabol)', description: 'y = ax² + bx + c formunda parabolün kolları, tepe noktası T(r,k), diskriminant (Δ) ve köklerin konumu.', category: 'AYT', subject: 'Matematik', topic: 'Parabol', difficulty_level: 3, related_yks_topics: ['Parabol Tepe Noktası', 'Simetri Ekseni', 'Kökler ve Diskriminant'], badge: 'AYT Banko', has_turkish: true, is_active: true },
  { slug: 'birim-oran-hiz', phet_id: 'unit-rates', title_tr: 'Birim Oran & Hız-Zaman Problemleri', description: 'Birim fiyat, ortalama hız, orantı sabiti ve çift sayı doğrusuyla hareket ve işçi problemleri mantığı.', category: 'TYT', subject: 'Matematik', topic: 'Problemler', difficulty_level: 2, related_yks_topics: ['Oran Orantı', 'Hız Problemleri', 'Birim Fiyat'], badge: 'TYT Problemler', has_turkish: true, is_active: true },

  // ─── FİZİK LİSE MÜFREDAT GENİŞLETME (PhET benzersiz ID'ler) ────────────────
  { slug: 'hareket-grafikleri', phet_id: 'the-moving-man', title_tr: 'Hareket Grafikleri (Konum-Zaman)', description: 'Sabit hızlı ve ivmeli hareketin konum, hız ve ivme grafiklerini canlı çizerek yorumla.', category: 'TYT', subject: 'Fizik', topic: 'Hareket', difficulty_level: 1, related_yks_topics: ['Konum-Zaman Grafiği', 'Hız-Zaman Grafiği', 'İvme'], badge: 'TYT Temel', has_turkish: true, is_active: false },
  { slug: 'ladybug-hareket', phet_id: 'ladybug-motion-2d', title_tr: 'Uğur Böceği ile 2B Hareket', description: 'İki boyutlu hareket, hız vektörleri ve konum-zaman ilişkisini interaktif incele.', category: 'TYT', subject: 'Fizik', topic: 'Hareket', difficulty_level: 2, related_yks_topics: ['Vektörel Hız', 'Konum Vektörü', '2B Hareket'], badge: 'TYT Fizik', has_turkish: true, is_active: false },
  { slug: 'kuvvet-hareket-detay', phet_id: 'forces-and-motion', title_tr: 'Kuvvet ve Hareket (Detaylı Newton)', description: 'Sürtünmeli yüzey, uygulanan kuvvet ve kütle ile F_net = m·a ilişkisini grafikle keşfet.', category: 'TYT', subject: 'Fizik', topic: 'Dinamik', difficulty_level: 2, related_yks_topics: ['Newton 2. Yasa', 'Net Kuvvet', 'Sürtünme'], badge: 'TYT Banko', has_turkish: true, is_active: false },
  { slug: 'tork-denge-detay', phet_id: 'torque', title_tr: 'Tork ve Dönme Dengesi', description: 'Kuvvet kolu, tork yönü ve dönme dengesini tahterevalli modeliyle öğren.', category: 'AYT', subject: 'Fizik', topic: 'Tork ve Denge', difficulty_level: 3, related_yks_topics: ['Tork', 'Dönme Dengesi', 'Moment'], badge: 'AYT Mekanik', has_turkish: true, is_active: false },
  { slug: 'kutlecekim-temel', phet_id: 'gravity-force-lab-basics', title_tr: 'Kütle Çekimi Temelleri', description: 'İki kütle arasındaki çekim kuvvetinin kütle ve uzaklıkla değişimini sade modelle gör.', category: 'TYT', subject: 'Fizik', topic: 'Evrensel Çekim', difficulty_level: 1, related_yks_topics: ['Kütle Çekim', 'Ters Kare Yasası', 'Gravitasyon'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'maddenin-halleri-temel', phet_id: 'states-of-matter-basics', title_tr: 'Maddenin Halleri (Temel)', description: 'Neon, argon ve oksijen atomlarıyla katı-sıvı-gaz geçişlerini temel seviyede keşfet.', category: 'TYT', subject: 'Fizik', topic: 'Madde ve Özellikleri', difficulty_level: 1, related_yks_topics: ['Maddenin Halleri', 'Isıtma-Soğutma', 'Tanecik Modeli'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'yaylar-temel', phet_id: 'masses-and-springs-basics', title_tr: 'Yaylar ve Kütleler (Temel)', description: 'Yay sabiti ve kütle ile uzama, periyot ve enerji ilişkisini temel seviyede incele.', category: 'TYT', subject: 'Fizik', topic: 'Esneklik', difficulty_level: 1, related_yks_topics: ['Hooke Yasası', 'Periyot', 'Esneklik Enerjisi'], badge: 'TYT Fizik', has_turkish: true, is_active: true },
  { slug: 'elektrik-hokeyi', phet_id: 'electric-hockey', title_tr: 'Elektrik Hokeyi (Alan Oyunu)', description: 'Pozitif ve negatif yükleri dizerek topu kaleye sok; elektrik alan çizgilerini oyunla öğren.', category: 'AYT', subject: 'Fizik', topic: 'Elektrostatik', difficulty_level: 3, related_yks_topics: ['Elektrik Alan', 'Coulomb Kuvveti', 'Alan Çizgileri'], badge: 'AYT Elektrik', has_turkish: true, is_active: false },
  { slug: 'pil-gerilimi', phet_id: 'battery-voltage', title_tr: 'Pil Gerilimi & Elektrot', description: 'Pil içi kimyasal yapı ile uçlar arası gerilim ilişkisini görselleştir.', category: 'TYT', subject: 'Fizik', topic: 'Elektrik Akımı', difficulty_level: 1, related_yks_topics: ['Pil', 'Gerilim', 'Elektrot'], badge: 'TYT Temel', has_turkish: true, is_active: false },
  { slug: 'basit-devre', phet_id: 'battery-resistor-circuit', title_tr: 'Basit Elektrik Devresi', description: 'Tek pil ve dirençle akım-gerilim-direnci ilişkisini sade devrede test et.', category: 'TYT', subject: 'Fizik', topic: 'Elektrik Devreleri', difficulty_level: 1, related_yks_topics: ['Ohm Yasası', 'Akım', 'Direnç'], badge: 'TYT Temel', has_turkish: true, is_active: false },
  { slug: 'devre-sanal-lab', phet_id: 'circuit-construction-kit-dc-virtual-lab', title_tr: 'Devre Sanal Laboratuvarı (DC)', description: 'Gerçekçi laboratuvar tezgahında seri-paralel devre kur, ölçüm yap.', category: 'TYT', subject: 'Fizik', topic: 'Elektrik Devreleri', difficulty_level: 2, related_yks_topics: ['Seri Devre', 'Paralel Devre', 'Ölçüm'], badge: 'TYT/AYT', has_turkish: true, is_active: true },
  { slug: 'sigac-detay-lab', phet_id: 'capacitor-lab', title_tr: 'Sığaç Laboratuvarı (Detay)', description: 'Plaka alanı ve dielektrik ile sığa, yük ve enerji depolamayı detaylı incele.', category: 'AYT', subject: 'Fizik', topic: 'Sığaçlar', difficulty_level: 4, related_yks_topics: ['Sığa', 'Dielektrik', 'Enerji'], badge: 'AYT Elektrik', has_turkish: false, is_active: false },
  { slug: 'jenerator-ac', phet_id: 'generator', title_tr: 'AC Jeneratörü & İndüksiyon', description: 'Mıknatıs döndürerek alternatif gerilim üretimi ve frekans-amplitüd ilişkisi.', category: 'AYT', subject: 'Fizik', topic: 'Alternatif Akım', difficulty_level: 3, related_yks_topics: ['Jeneratör', 'Alternatif Akım', 'Frekans'], badge: 'AYT Elektrik', has_turkish: false, is_active: true },
  { slug: 'rezonans-dalgalar', phet_id: 'resonance', title_tr: 'Rezonans & Duran Dalgalar', description: 'Farklı frekanslarda rezonans oluşumu ve duran dalga desenlerini gözle.', category: 'AYT', subject: 'Fizik', topic: 'Dalgalar', difficulty_level: 3, related_yks_topics: ['Rezonans', 'Duran Dalga', 'Doğal Frekans'], badge: 'AYT Dalgalar', has_turkish: false, is_active: false },
  { slug: 'geometrik-optik-temel', phet_id: 'geometric-optics-basics', title_tr: 'Geometrik Optik (Temel)', description: 'Işın kutusu ile ayna ve mercekte yansıma-kırılmayı temel seviyede öğren.', category: 'TYT', subject: 'Fizik', topic: 'Optik', difficulty_level: 1, related_yks_topics: ['Yansıma', 'Kırılma', 'Mercek'], badge: 'TYT Optik', has_turkish: true, is_active: true },
  { slug: 'lazerler', phet_id: 'lasers', title_tr: 'Lazerler & Uyarılmış Emisyon', description: 'Atomik enerji seviyeleri, foton emisyonu ve lazer ışığı oluşumu.', category: 'AYT', subject: 'Fizik', topic: 'Modern Fizik', difficulty_level: 4, related_yks_topics: ['Uyarılmış Emisyon', 'Foton', 'Enerji Seviyesi'], badge: 'AYT Modern', has_turkish: false, is_active: false },
  { slug: 'kuantum-girisim', phet_id: 'quantum-wave-interference', title_tr: 'Kuantum Dalga Girişimi', description: 'Elektron ve fotonların çift yarıkta girişim deseni ve olasılık dalgası.', category: 'AYT', subject: 'Fizik', topic: 'Modern Fizik', difficulty_level: 5, related_yks_topics: ['Dalga-Parçacık İkiliği', 'Girişim', 'Olasılık Dalgası'], badge: 'AYT Modern', has_turkish: false, is_active: true },
  { slug: 'kuantum-tunelleme', phet_id: 'quantum-tunneling', title_tr: 'Kuantum Tünelleme', description: 'Parçacığın potansiyel engelinden geçme olasılığı ve dalga fonksiyonu.', category: 'AYT', subject: 'Fizik', topic: 'Modern Fizik', difficulty_level: 5, related_yks_topics: ['Tünelleme', 'Dalga Fonksiyonu', 'Potansiyel Engel'], badge: 'AYT Modern', has_turkish: false, is_active: false },
  { slug: 'alfa-bozunmasi', phet_id: 'alpha-decay', title_tr: 'Alfa Bozunması', description: 'Ağır çekirdekten alfa ışıması, kütle ve atom numarası değişimi.', category: 'AYT', subject: 'Fizik', topic: 'Radyoaktivite', difficulty_level: 3, related_yks_topics: ['Alfa Işıması', 'Yarı Ömür', 'Çekirdek'], badge: 'AYT Modern', has_turkish: false, is_active: false },
  { slug: 'beta-bozunmasi', phet_id: 'beta-decay', title_tr: 'Beta Bozunması', description: 'Nötronun protona dönüşümü, beta ışıması ve nötrino kavramı.', category: 'AYT', subject: 'Fizik', topic: 'Radyoaktivite', difficulty_level: 4, related_yks_topics: ['Beta Işıması', 'Nötron-Proton', 'Bozunma'], badge: 'AYT Modern', has_turkish: false, is_active: false },
  { slug: 'cekirdek-olustur', phet_id: 'build-a-nucleus', title_tr: 'Çekirdek Oluştur & Bağlanma Enerjisi', description: 'Proton ve nötron ekleyerek çekirdek kararlılığı ve bağlanma enerjisini keşfet.', category: 'AYT', subject: 'Fizik', topic: 'Çekirdek Fiziği', difficulty_level: 3, related_yks_topics: ['Bağlanma Enerjisi', 'Kararlılık', 'İzotop'], badge: 'AYT Modern', has_turkish: false, is_active: true },
  { slug: 'atis-veri-labi', phet_id: 'projectile-data-lab', title_tr: 'Atış Veri Laboratuvarı', description: 'Eğik atış verilerini topla, menzil-hız-açı grafiklerini analiz et.', category: 'AYT', subject: 'Fizik', topic: 'Atışlar', difficulty_level: 3, related_yks_topics: ['Eğik Atış', 'Menzil', 'Veri Analizi'], badge: 'AYT Mekanik', has_turkish: false, is_active: true },

  // ─── KİMYA + BİYOLOJİ GENİŞLETME ──────────────────────────────────────────
  { slug: 'atom-etkilesim', phet_id: 'atomic-interactions', title_tr: 'Atom Etkileşimleri & Kimyasal Bağ', description: 'İki atomu yaklaştırıp uzaklaştırarak itme-çekme kuvvetleri ve bağ oluşumu.', category: 'TYT', subject: 'Kimya', topic: 'Kimyasal Bağlar', difficulty_level: 3, related_yks_topics: ['Kimyasal Bağ', 'Van der Waals', 'Bağ Enerjisi'], badge: 'TYT Kimya', has_turkish: true, is_active: true },
  { slug: 'molekul-sekilleri-temel', phet_id: 'molecule-shapes-basics', title_tr: 'Molekül Şekilleri (Temel)', description: 'Bağ çifti sayısıyla molekül geometrisini temel seviyede tahmin et.', category: 'TYT', subject: 'Kimya', topic: 'Kimyasal Bağlar', difficulty_level: 2, related_yks_topics: ['VSEPR', 'Molekül Geometrisi', 'Bağ Açısı'], badge: 'TYT Kimya', has_turkish: true, is_active: true },
  { slug: 'ph-olcegi-temel', phet_id: 'ph-scale-basics', title_tr: 'pH Ölçeği (Temel)', description: 'Günlük çözeltilerin asidik-bazik karakterini ve pH değerini karşılaştır.', category: 'TYT', subject: 'Kimya', topic: 'Asitler & Bazlar', difficulty_level: 1, related_yks_topics: ['pH', 'Asit', 'Baz'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'gen-makinesi-operon', phet_id: 'gene-machine-lac-operon', title_tr: 'Gen Makinesi (Lac Operon)', description: 'Bakteride gen açılıp kapanması, represör ve RNA polimeraz etkileşimi.', category: 'AYT', subject: 'Biyoloji', topic: 'Genetik Kontrol', difficulty_level: 4, related_yks_topics: ['Operon', 'Gen İfadesi', 'Represör'], badge: 'AYT Biyoloji', has_turkish: false, is_active: false },

  // ─── MATEMATİK LİSE GENİŞLETME ────────────────────────────────────────────
  { slug: 'denklik-kesfi', phet_id: 'equality-explorer', title_tr: 'Eşitlik Keşfi & Denklemler', description: 'Terazi modeliyle denklem kurma, eşitsizlik ve bilinmeyenli denklem çözme.', category: 'TYT', subject: 'Matematik', topic: 'Denklemler', difficulty_level: 2, related_yks_topics: ['Denklem Çözme', 'Eşitsizlik', 'Terazi Modeli'], badge: 'TYT Matematik', has_turkish: true, is_active: true },
  { slug: 'denklik-temel', phet_id: 'equality-explorer-basics', title_tr: 'Eşitlik Temelleri', description: 'Temel denklem kavramı ve eşitliğin korunumu ilkesini görsel öğren.', category: 'TYT', subject: 'Matematik', topic: 'Denklemler', difficulty_level: 1, related_yks_topics: ['Eşitlik', 'Denklem', 'Bilinmeyen'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'ifade-degisimi', phet_id: 'expression-exchange', title_tr: 'Cebirsel İfade Değişimi', description: 'Cebir karolarıyla benzer terimleri birleştirme ve özdeşlikleri modelleme.', category: 'TYT', subject: 'Matematik', topic: 'Cebir', difficulty_level: 2, related_yks_topics: ['Cebirsel İfade', 'Benzer Terim', 'Özdeşlik'], badge: 'TYT Matematik', has_turkish: true, is_active: true },
  { slug: 'en-kucuk-kareler', phet_id: 'least-squares-regression', title_tr: 'En Küçük Kareler & Regresyon', description: 'Veri noktalarına en uygun doğruyu çiz, artık kareler toplamını minimize et.', category: 'TYT', subject: 'Matematik', topic: 'İstatistik', difficulty_level: 3, related_yks_topics: ['Regresyon', 'Korelasyon', 'Veri Analizi'], badge: 'TYT Matematik', has_turkish: true, is_active: true },
  { slug: 'sayi-dogrusu', phet_id: 'number-line-integers', title_tr: 'Sayı Doğrusu & Tam Sayılar', description: 'Negatif ve pozitif tam sayılarla toplama-çıkarma işlemlerini görselleştir.', category: 'TYT', subject: 'Matematik', topic: 'Sayılar', difficulty_level: 1, related_yks_topics: ['Tam Sayılar', 'Sayı Doğrusu', 'Mutlak Değer'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'oran-oranti-detay', phet_id: 'ratio-and-proportion', title_tr: 'Oran ve Orantı (Detay)', description: 'Eller ve boyalarla oran-orantı, birim oran ve ölçek problemleri.', category: 'TYT', subject: 'Matematik', topic: 'Oran ve Orantı', difficulty_level: 2, related_yks_topics: ['Oran', 'Orantı', 'Ölçek'], badge: 'TYT Matematik', has_turkish: true, is_active: true },
  { slug: 'kesir-esdeger', phet_id: 'fractions-equality', title_tr: 'Denk Kesirler & Sıralama', description: 'Farklı modellenmiş kesirlerin denkliğini bul ve sayı doğrusunda sırala.', category: 'TYT', subject: 'Matematik', topic: 'Rasyonel Sayılar', difficulty_level: 1, related_yks_topics: ['Denk Kesir', 'Sıralama', 'Karşılaştırma'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'vektor-denklem', phet_id: 'vector-addition-equations', title_tr: 'Vektör Denklemleri', description: 'Bileşen denklemleriyle vektör toplama ve büyüklük-yön hesabı.', category: 'AYT', subject: 'Matematik', topic: 'Vektörler', difficulty_level: 3, related_yks_topics: ['Vektör Bileşeni', 'Büyüklük', 'Yön Açısı'], badge: 'AYT Matematik', has_turkish: false, is_active: true },
  { slug: 'fonksiyon-temel', phet_id: 'function-builder-basics', title_tr: 'Fonksiyon Oluşturucu (Temel)', description: 'Şekil ve sayı örüntüleriyle fonksiyon kuralı oluşturma ve tersini bulma.', category: 'TYT', subject: 'Matematik', topic: 'Fonksiyonlar', difficulty_level: 1, related_yks_topics: ['Fonksiyon', 'Örüntü', 'Kural Bulma'], badge: 'TYT Temel', has_turkish: true, is_active: true },
];

// Slug'a göre simülasyon bul
export function findSimBySlug(slug: string): PhetSim | undefined {
  return PHET_REGISTRY.find(s => s.slug === slug);
}

// Kategoriye göre filtrele
export function filterPhetSims(params: {
  category?: string;
  subject?: string;
  difficulty?: number;
  search?: string;
}): PhetSim[] {
  let sims = [...PHET_REGISTRY];
  if (params.category && params.category !== 'Tümü') {
    sims = sims.filter(s => s.category === params.category || s.category === 'TYT/AYT');
  }
  if (params.subject && params.subject !== 'Tümü') {
    sims = sims.filter(s => s.subject === params.subject);
  }
  if (params.difficulty && params.difficulty !== 0) {
    sims = sims.filter(s => s.difficulty_level === params.difficulty);
  }
  if (params.search && params.search.trim()) {
    const q = params.search.trim().toLowerCase();
    sims = sims.filter(s =>
      s.title_tr.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q) ||
      s.topic.toLowerCase().includes(q) ||
      s.related_yks_topics.some(t => t.toLowerCase().includes(q))
    );
  }
  return sims;
}
