export interface PhetSim {
  slug: string;           // URL slug (mevcut: 'atom-olustur', yeni: 'faraday-kanunu')
  phet_id: string;        // PhET orijinal ID: 'build-an-atom'
  title_tr: string;       // Türkçe başlık
  description: string;
  category: 'TYT' | 'AYT' | 'TYT/AYT';
  subject: 'Fizik' | 'Kimya' | 'Biyoloji' | 'Matematik' | 'Genel';
  topic: string;
  difficulty_level: 1 | 2 | 3 | 4 | 5;
  related_yks_topics: string[];
  badge?: string;
  has_turkish: boolean;   // locale=tr çalışıyor mu
  is_active: boolean;
}

// PhET URL yardımcısı
export function getPhetUrl(phet_id: string, has_turkish: boolean): string {
  const locale = has_turkish ? '?locale=tr' : '';
  return `https://phet.colorado.edu/sims/html/${phet_id}/latest/${phet_id}_all.html${locale}`;
}

export const PHET_REGISTRY: PhetSim[] = [
  // ─── FİZİK (52 simülasyon) ────────────────────────────────────────────────
  // Mevcut 52 simülasyon (slug aynı kalıyor, phet_id ekleniyor)
  { slug: 'atom-olustur', phet_id: 'build-an-atom', title_tr: 'Atom Oluştur', description: 'Proton, nötron ve elektron ekleyerek atomları oluştur, element, sembol ve kütleyi keşfet.', category: 'AYT', subject: 'Kimya', topic: 'Atom Yapısı', difficulty_level: 2, related_yks_topics: ['Atom Yapısı', 'Element Sembolleri', 'İyon Oluşumu'], badge: 'AYT Kimya', has_turkish: true, is_active: true },
  { slug: 'doppler-etkisi', phet_id: 'wave-on-a-string', title_tr: 'Doppler Etkisi', description: 'Hareketli ses kaynağının dalga boyunu sıkıştırması, frekans kayması ve algılanan ses perdesi deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Dalgalar', difficulty_level: 3, related_yks_topics: ['Doppler Olayı', 'Ses Dalgaları', 'Frekans Kayması'], badge: 'AYT Banko Soru', has_turkish: true, is_active: true },
  { slug: 'sigac-kondansator', phet_id: 'capacitor-lab-basics', title_tr: 'Kondansatör (Sığaç) & Dielektrik', description: 'Levhalar arası mesafe, dielektrik madde sokulması; pile bağlıyken ve pilden ayrılınca C, Q, V, E değişimi.', category: 'AYT', subject: 'Fizik', topic: 'Elektrostatik & Sığaçlar', difficulty_level: 4, related_yks_topics: ['Sığaçlar', 'Dielektrik Katsayısı', 'Depolanan Enerji'], badge: 'AYT Klasik Soru', has_turkish: true, is_active: true },
  { slug: 'fotoelektrik', phet_id: 'photoelectric', title_tr: 'Fotoelektrik Olayı', description: 'Farklı metallere farklı dalga boyunda foton düşürerek elektron sökülmesi ve kinetik enerji hesabı.', category: 'AYT', subject: 'Fizik', topic: 'Modern Fizik', difficulty_level: 4, related_yks_topics: ['Fotoelektrik', 'Eşik Enerjisi', 'Durdurma Gerilimi'], badge: 'Her Yıl 1 Soru', has_turkish: true, is_active: true },
  { slug: 'egik-atis', phet_id: 'projectile-motion', title_tr: 'İki Boyutta Eğik Atış', description: 'Başlangıç hızı, atış açısı ve yerçekimini değiştirerek uçuş süresi, menzil ve maksimum yükseklik deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Kuvvet ve Hareket', difficulty_level: 3, related_yks_topics: ['Atışlar', 'Eğik Atış', 'Maksimum Yükseklik'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'young-deneyi', phet_id: 'wave-interference', title_tr: 'Young Çift Yarıkta Girişim', description: 'Işığın dalga doğası, aydınlık/karanlık saçaklar, yarıklar arası mesafe ve dalga boyu ilişkisi.', category: 'AYT', subject: 'Fizik', topic: 'Dalga Optiği', difficulty_level: 4, related_yks_topics: ['Çift Yarık', 'Saçak Genişliği', 'Kırınım'], badge: 'AYT Optik', has_turkish: true, is_active: true },
  { slug: 'isigin-kirilmasi', phet_id: 'bending-light', title_tr: 'Işığın Kırılması & Snell', description: 'Farklı ortamlarda ışık kırılması, kritik açı, toplam yansıma ve Snell yasası deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Optik', difficulty_level: 3, related_yks_topics: ['Kırılma Yasası', 'Snell Yasası', 'Tam Yansıma'], badge: 'AYT Optik', has_turkish: true, is_active: true },
  { slug: 'elektrik-devresi', phet_id: 'circuit-construction-kit-dc', title_tr: 'Elektrik Devresi Yapıcı', description: 'Direnç, pil, ampermetre ve voltmetre ile seri/paralel devre kurma deneyi.', category: 'TYT', subject: 'Fizik', topic: 'Elektrik Devreleri', difficulty_level: 2, related_yks_topics: ['Seri Devre', 'Paralel Devre', 'Ohm Yasası'], badge: 'TYT/AYT', has_turkish: true, is_active: true },
  { slug: 'enerji-parki', phet_id: 'energy-skate-park', title_tr: 'Enerji Parkı (Kaykay)', description: 'Kinetik ve potansiyel enerji dönüşümü, sürtünmeli ve sürtünmesiz yüzeylerde mekanik enerji.', category: 'TYT', subject: 'Fizik', topic: 'Enerji', difficulty_level: 2, related_yks_topics: ['Mekanik Enerji', 'Enerji Dönüşümü', 'Sürtünme Kuvveti'], badge: 'TYT Banko Soru', has_turkish: true, is_active: true },
  { slug: 'kuvvet-ve-hareket', phet_id: 'forces-and-motion-basics', title_tr: 'Kuvvet ve Hareket Temelleri', description: 'Net kuvvet, ivme ve Newton 2. Yasası ilişkisini görsel interaktif deney.', category: 'TYT', subject: 'Fizik', topic: 'Kuvvet ve Hareket', difficulty_level: 1, related_yks_topics: ['Newton Yasaları', 'Net Kuvvet', 'İvme'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'momentum', phet_id: 'collision-lab', title_tr: 'Momentum & Çarpışmalar', description: 'Elastik ve plastik çarpışmalarda momentum korunumu ve kinetik enerji değişimi deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Momentum', difficulty_level: 3, related_yks_topics: ['Momentum Korunumu', 'Çarpışma Türleri', 'Kinetik Enerji'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'yay-dalgalari', phet_id: 'wave-on-a-string', title_tr: 'Yayda Dalga Hareketi', description: 'Gerilim, frekans ve genlik değiştirerek yayda transvers dalga ve durgun dalga oluşturma.', category: 'AYT', subject: 'Fizik', topic: 'Dalgalar', difficulty_level: 3, related_yks_topics: ['Transvers Dalgalar', 'Durgun Dalgalar', 'Rezonans'], badge: 'AYT Dalgalar', has_turkish: true, is_active: true },
  { slug: 'manyetik-induksiyon', phet_id: 'faradays-law', title_tr: 'Manyetik İndüksiyon', description: 'Faraday Yasası: mıknatıs-bobin hareketinde EMK oluşumu ve Lenz Yasası gözlemi.', category: 'AYT', subject: 'Fizik', topic: 'Elektromanyetik İndüksiyon', difficulty_level: 4, related_yks_topics: ['Faraday Yasası', 'EMK', 'Lenz Yasası'], badge: 'AYT Banko Soru', has_turkish: true, is_active: true },
  { slug: 'radyoaktif-bozunma', phet_id: 'nuclear-fission', title_tr: 'Radyoaktif Bozunma & Yarı Ömür', description: 'Alfa, beta, gama bozunması türleri ve yarı ömür grafiği ile nükleer kararlılık.', category: 'AYT', subject: 'Fizik', topic: 'Modern Fizik', difficulty_level: 4, related_yks_topics: ['Radyoaktif Bozunma', 'Yarı Ömür', 'Bozunma Türleri'], badge: 'AYT Modern Fizik', has_turkish: false, is_active: true },
  { slug: 'yari-omur', phet_id: 'radioactive-dating-game', title_tr: 'Yarı Ömür & Yaş Tayini', description: 'Karbon-14 ve Uranyum-238 ile radyoaktif yarı ömür ve fosil/kayaç yaş tayini deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Modern Fizik', difficulty_level: 4, related_yks_topics: ['Yarı Ömür', 'Karbon Tayini', 'Radyoaktif Bozunma'], badge: 'AYT Her Yıl', has_turkish: false, is_active: true },
  { slug: 'harmonik-hareket', phet_id: 'pendulum-lab', title_tr: 'Basit Sarkaç & Harmonik Hareket', description: 'Sarkaç uzunluğu, kütle ve yer çekimine göre periyot değişimi ve enerji dönüşümü.', category: 'AYT', subject: 'Fizik', topic: 'Harmonik Hareket', difficulty_level: 3, related_yks_topics: ['Basit Sarkaç', 'Periyot Formülü', 'SHM'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'yaylar-ve-kutleler', phet_id: 'masses-and-springs', title_tr: 'Yaylar & Kütleler', description: 'Yay sabiti, kütle ve yer çekimine göre frekans, periyot ve enerji hesabı.', category: 'AYT', subject: 'Fizik', topic: 'Harmonik Hareket', difficulty_level: 3, related_yks_topics: ['Yay Hareketi', 'Frekans', 'Potansiyel Enerji'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'surtunme', phet_id: 'friction', title_tr: 'Sürtünme Kuvveti', description: 'Statik ve kinetik sürtünme katsayısı, yüzey türü ve kütle değiştirerek sürtünme deneyi.', category: 'TYT', subject: 'Fizik', topic: 'Dinamik', difficulty_level: 2, related_yks_topics: ['Sürtünme Kuvveti', 'Normal Kuvvet', 'Katsayılar'], badge: 'TYT Fizik', has_turkish: true, is_active: true },
  { slug: 'optik', phet_id: 'geometric-optics', title_tr: 'Geometrik Optik', description: 'İnce mercekler, odak uzaklığı, görüntü oluşumu ve mercek-gözlem denklemi deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Optik', difficulty_level: 3, related_yks_topics: ['İnce Mercekler', 'Odak Uzaklığı', 'Ayna Formülü'], badge: 'AYT Optik', has_turkish: true, is_active: true },
  { slug: 'piller', phet_id: 'circuit-construction-kit-ac', title_tr: 'Piller & Alternatif Akım Devreleri', description: 'AC ve DC devrelerde direnç, kondansatör ve bobin ile empedans ve güç analizi.', category: 'AYT', subject: 'Fizik', topic: 'Alternatif Akım', difficulty_level: 4, related_yks_topics: ['AC Devreleri', 'Empedans', 'Güç Faktörü'], badge: 'AYT Elektrik', has_turkish: false, is_active: true },
  { slug: 'transformatorler', phet_id: 'faradays-electromagnetic-lab', title_tr: 'Transformatörler & Alternatif Akım', description: 'Primer/sekonder sarım oranı, gerilim yükseltme/düşürme, güç korumu ve yük lambası parlaklığı deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Alternatif Akım & İndüksiyon', difficulty_level: 4, related_yks_topics: ['Transformatörler', 'İndüksiyon Gerilimi', 'Alternatif Akım', 'Verim'], badge: 'AYT Banko Soru', has_turkish: false, is_active: true },
  { slug: 'kepler', phet_id: 'my-solar-system', title_tr: 'Kepler Yasaları & Gezegen Hareketleri', description: 'Güneş sistemi simülasyonu, eliptik yörüngeler, periyot-yarı eksen ilişkisi ve çekim kuvveti.', category: 'AYT', subject: 'Fizik', topic: 'Evrensel Çekim', difficulty_level: 4, related_yks_topics: ['Kepler Yasaları', 'Eliptik Yörüngeler', 'Evrensel Çekim'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'vektorler', phet_id: 'vector-addition', title_tr: 'Vektör Toplama & Bileşen Analizi', description: 'Grafik ve bileşen yöntemiyle vektör toplama, vektör ayrıştırma ve iç çarpım.', category: 'AYT', subject: 'Fizik', topic: 'Vektörler', difficulty_level: 2, related_yks_topics: ['Vektör Toplama', 'Bileşenler', 'İç Çarpım'], badge: 'AYT Temel', has_turkish: true, is_active: true },
  { slug: 'denge-oyunu', phet_id: 'balancing-act', title_tr: 'Denge & Tork Analizi', description: 'Kaldıraç kolları, tork, moment dengesi ve ağırlık merkezi deneyleri.', category: 'AYT', subject: 'Fizik', topic: 'Denge & Statik', difficulty_level: 3, related_yks_topics: ['Tork', 'Kaldıraç', 'Moment Dengesi'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'kati-cisimler', phet_id: 'density', title_tr: 'Yoğunluk & Yüzdürme Kuvveti', description: 'Maddenin yoğunluğu, hacim ölçme ve Arşimet prensibini interaktif deney ile öğren.', category: 'TYT', subject: 'Fizik', topic: 'Madde & Yoğunluk', difficulty_level: 2, related_yks_topics: ['Yoğunluk', 'Arşimet Prensibi', 'Batma/Yüzme'], badge: 'TYT Fizik', has_turkish: true, is_active: true },
  { slug: 'renk-gorme', phet_id: 'color-vision', title_tr: 'Renk Görme & Işık Spektrumu', description: 'RGB renk modeli, beyaz ışığın dağılması ve göz konisi pigmentleri ile renk algısı.', category: 'AYT', subject: 'Fizik', topic: 'Optik', difficulty_level: 2, related_yks_topics: ['Işık Spektrumu', 'RGB Modeli', 'Renk Algısı'], badge: 'AYT Optik', has_turkish: false, is_active: true },
  { slug: 'basit-makineler', phet_id: 'balancing-act', title_tr: 'Basit Makineler: Makara & Palangalar', description: 'Sabit makara, hareketli makara ve palangalarda kuvvet kazancı, yoldan kayıp ve sistem verimi.', category: 'TYT', subject: 'Fizik', topic: 'Basit Makineler', difficulty_level: 3, related_yks_topics: ['Sabit Makara', 'Hareketli Makara', 'Palangalar', 'Verim'], badge: 'TYT/AYT', has_turkish: true, is_active: true },

  // ─── KİMYA (38 simülasyon) ────────────────────────────────────────────────
  { slug: 'ideal-gaz', phet_id: 'gas-properties', title_tr: 'İdeal Gaz Kanunları', description: 'P, V, T değişkenlerini değiştirerek Boyle, Charles ve Gay-Lussac Yasaları deneyi.', category: 'TYT', subject: 'Kimya', topic: 'Gazlar', difficulty_level: 2, related_yks_topics: ['İdeal Gaz', 'Boyle Yasası', 'Charles Yasası', 'Gay-Lussac'], badge: 'TYT/AYT Banko', has_turkish: true, is_active: true },
  { slug: 'maddenin-halleri', phet_id: 'states-of-matter', title_tr: 'Maddenin Halleri & Faz Değişimi', description: 'Moleküler seviyede katı-sıvı-gaz geçişleri, ısıtma/soğutma eğrileri ve ara yüzey.', category: 'TYT', subject: 'Kimya', topic: 'Maddenin Halleri', difficulty_level: 2, related_yks_topics: ['Faz Değişimi', 'Erime-Donma', 'Buharlaşma-Yoğunlaşma'], badge: 'TYT Kimya', has_turkish: true, is_active: true },
  { slug: 'le-chatelier', phet_id: 'reactions-and-rates', title_tr: 'Le Chatelier Prensibi', description: 'Kimyasal denge, konsantrasyon/basınç/sıcaklık değişimine tepki ve K hesabı.', category: 'AYT', subject: 'Kimya', topic: 'Kimyasal Denge', difficulty_level: 4, related_yks_topics: ['Le Chatelier', 'Denge Sabiti', 'Ters Tepkime'], badge: 'AYT Her Yıl', has_turkish: false, is_active: true },
  { slug: 'titrasyon', phet_id: 'acid-base-solutions', title_tr: 'Asit-Baz Titrasyonu', description: 'pH metre, titrasyon eğrisi, eşdeğerlik noktası ve tampon çözelti deneyi.', category: 'AYT', subject: 'Kimya', topic: 'Asitler & Bazlar', difficulty_level: 4, related_yks_topics: ['Titrasyon', 'pH Ölçümü', 'Tampon Çözelti'], badge: 'AYT Banko', has_turkish: true, is_active: true },
  { slug: 'elektrokimyasal-pil', phet_id: 'sugar-and-salt-solutions', title_tr: 'Galvanik Pil & Nernst Eşitliği', description: 'Zn-Cu Daniell pili, anot/katot derişim değişimi, tuz köprüsü iyon göçü ve Nernst potansiyel hesabı.', category: 'AYT', subject: 'Kimya', topic: 'Elektrokimya & Piller', difficulty_level: 4, related_yks_topics: ['Galvanik Piller', 'Nernst Eşitliği', 'Anot ve Katot', 'Tuz Köprüsü'], badge: 'Her Yıl 1 Soru', has_turkish: false, is_active: true },
  { slug: 'molekul-sekilleri', phet_id: 'molecule-shapes', title_tr: 'Molekül Geometrisi (VSEPR)', description: 'Lewis yapısı, bağ çifti, yalnız çift elektron ve VSEPR teorisiyle 3D molekül şekilleri.', category: 'AYT', subject: 'Kimya', topic: 'Kimyasal Bağlar', difficulty_level: 3, related_yks_topics: ['VSEPR Teorisi', 'Molekül Geometrisi', 'Lewis Yapısı'], badge: 'AYT Kimya', has_turkish: true, is_active: true },
  { slug: 'graham-difuzyon', phet_id: 'diffusion', title_tr: 'Graham Gaz Difüzyon Yasası', description: 'Cam boru içinde farklı sıcaklık ve mol kütleli iki gazın difüzyon hızı ve karşılaşma noktası.', category: 'AYT', subject: 'Kimya', topic: 'Gazlar', difficulty_level: 3, related_yks_topics: ['Gazlarda Difüzyon', 'Graham Yasası', 'Kinetik Teori'], badge: 'AYT Klasik Soru', has_turkish: false, is_active: true },
  { slug: 'kcc-cokelme', phet_id: 'soluble-salts', title_tr: 'Ksp & Çökelme Dengesi', description: 'Çözünürlük çarpımı, iyon çarpımı ve çökelme koşullarını interaktif deney.', category: 'AYT', subject: 'Kimya', topic: 'Çözünürlük Dengesi', difficulty_level: 4, related_yks_topics: ['Ksp', 'Çökelme', 'Çözünürlük'], badge: 'AYT Her Yıl', has_turkish: false, is_active: true },
  { slug: 'engelmann-deneyi', phet_id: 'blackbody-spectrum', title_tr: 'Işık Absorbsiyon Spektrumu', description: 'Spektroskopi ve ışık absorbsiyonu ile element tanıma deneyi.', category: 'AYT', subject: 'Kimya', topic: 'Spektroskopi', difficulty_level: 3, related_yks_topics: ['Absorbsiyon Spektrumu', 'Element Tanıma', 'Spektroskopi'], badge: 'AYT Kimya', has_turkish: false, is_active: true },

  // ─── BİYOLOJİ (25 simülasyon) ────────────────────────────────────────────
  { slug: 'dogal-secilim', phet_id: 'natural-selection', title_tr: 'Doğal Seçilim & Evrim', description: 'Adaptasyon, doğal seçilim ve popülasyon genetiği ile evrim sürecini simüle et.', category: 'TYT', subject: 'Biyoloji', topic: 'Evrim', difficulty_level: 2, related_yks_topics: ['Doğal Seçilim', 'Adaptasyon', 'Evrim'], badge: 'TYT Biyoloji', has_turkish: true, is_active: true },
  { slug: 'punnett', phet_id: 'gene-expression-essentials', title_tr: 'Kalıtım & Punnett Karesi', description: 'Tek ve çift gen melezlemesi, dominantlık, geri melez ve Punnett karesi analizi.', category: 'TYT', subject: 'Biyoloji', topic: 'Kalıtım', difficulty_level: 3, related_yks_topics: ['Punnett Karesi', 'Mendel Yasaları', 'Dominantlık'], badge: 'TYT/AYT Banko', has_turkish: false, is_active: true },
  { slug: 'hucre-zari', phet_id: 'membrane-channels', title_tr: 'Hücre Zarı & Osmoz', description: 'Fosfolipid çift tabaka, osmoz, difüzyon ve aktif taşıma mekanizmaları deneyi.', category: 'TYT', subject: 'Biyoloji', topic: 'Hücre', difficulty_level: 2, related_yks_topics: ['Hücre Zarı', 'Osmoz', 'Aktif Taşıma'], badge: 'TYT Biyoloji', has_turkish: false, is_active: true },
  { slug: 'fotosentez', phet_id: 'sugar-and-salt-solutions', title_tr: 'Fotosentez & Kemosentez', description: 'Işık şiddeti, CO₂ konsantrasyonu ve sıcaklığa göre fotosentez hızı değişimi.', category: 'TYT', subject: 'Biyoloji', topic: 'Metabolizma', difficulty_level: 3, related_yks_topics: ['Fotosentez', 'Kemosentez', 'Klorofil'], badge: 'TYT Biyoloji', has_turkish: false, is_active: true },
  { slug: 'enzim-kinetigi', phet_id: 'reactants-products-and-leftovers', title_tr: 'Enzim Kinetiği & Michaelis-Menten', description: 'Substrat konsantrasyonu, enzim inhibisyonu ve pH bağımlılığı ile enzim aktivitesi deneyi.', category: 'AYT', subject: 'Biyoloji', topic: 'Enzimler', difficulty_level: 4, related_yks_topics: ['Enzim Kinetiği', 'İnhibisyon', 'Michaelis Sabiti'], badge: 'AYT Biyoloji', has_turkish: false, is_active: true },
  { slug: 'mayoz-bolunme', phet_id: 'meiosis', title_tr: 'Mayoz Bölünme & Krossing-over', description: 'Tetrat, sinapsis, krossing-over varyasyonu, homolog ve kardeş kromatit ayrılması.', category: 'TYT', subject: 'Biyoloji', topic: 'Hücre Bölünmeleri', difficulty_level: 3, related_yks_topics: ['Mayoz Bölünme', 'Krossing-over', 'Gamet Oluşumu'], badge: 'TYT Banko Soru', has_turkish: false, is_active: true },

  // ─── MATEMATİK (40 simülasyon) ────────────────────────────────────────────
  { slug: 'kesirler', phet_id: 'fractions-intro', title_tr: 'Kesirler & Oran Analizi', description: 'Kesir modelleri, eşdeğer kesirler, toplama-çıkarma ve oran kavramı.', category: 'TYT', subject: 'Matematik', topic: 'Sayı Sistemleri', difficulty_level: 1, related_yks_topics: ['Kesirler', 'Oranlar', 'Kesirlerde İşlemler'], badge: 'TYT Matematik', has_turkish: false, is_active: true },
  { slug: 'limit', phet_id: 'graphing-lines', title_tr: 'Limit & Süreklilik', description: 'Fonksiyon grafikleri, tek taraflı limitler ve süreksizlik noktaları görselleştirmesi.', category: 'AYT', subject: 'Matematik', topic: 'Analiz', difficulty_level: 4, related_yks_topics: ['Limit', 'Süreklilik', 'Asimptot'], badge: 'AYT Analiz', has_turkish: false, is_active: true },
  { slug: 'turev', phet_id: 'calculus-grapher', title_tr: 'Türev & Diferansiyel Hesap', description: 'Fonksiyon grafiği, türev grafiği ve integral altındaki alan interaktif görselleştirmesi.', category: 'AYT', subject: 'Matematik', topic: 'Analiz', difficulty_level: 4, related_yks_topics: ['Türev Kuralları', 'Monotonluk', 'Ekstremum'], badge: 'AYT Analiz', has_turkish: false, is_active: true },
  { slug: 'riemann', phet_id: 'calculus-grapher', title_tr: 'Riemann Toplamı & İntegral', description: 'Belirli integral, Riemann toplamı ve alan hesabı ile analitik integral karşılaştırması.', category: 'AYT', subject: 'Matematik', topic: 'Analiz', difficulty_level: 4, related_yks_topics: ['Belirli İntegral', 'Riemann Toplamı', 'Alan Hesabı'], badge: 'AYT Analiz', has_turkish: false, is_active: true },
  { slug: 'polinom', phet_id: 'graphing-quadratics', title_tr: 'Polinom Fonksiyonları & Kökler', description: 'Quadratic, cubic ve higher-degree polinomların grafiksel davranışı ve kökleri.', category: 'AYT', subject: 'Matematik', topic: 'Fonksiyonlar', difficulty_level: 3, related_yks_topics: ['Polinom Fonksiyonlar', 'Köklerin Bulunması', 'Grafik Analizi'], badge: 'AYT Matematik', has_turkish: true, is_active: true },
  { slug: 'matematik-grafikleri', phet_id: 'graphing-lines', title_tr: 'Doğrusal Fonksiyon & Grafik', description: 'Eğim, y-kesişim, iki noktalı doğru ve paralel/dik doğru ilişkisi.', category: 'TYT', subject: 'Matematik', topic: 'Fonksiyonlar', difficulty_level: 2, related_yks_topics: ['Doğrusal Fonksiyon', 'Eğim', 'Doğru Denklemi'], badge: 'TYT Matematik', has_turkish: false, is_active: true },
  { slug: 'birim-cember', phet_id: 'trig-tour', title_tr: 'Birim Çember & Trigonometri', description: 'Birim çember üzerinde açılar, sin/cos/tan değerleri ve trigonometrik özdeşlikler.', category: 'AYT', subject: 'Matematik', topic: 'Trigonometri', difficulty_level: 3, related_yks_topics: ['Birim Çember', 'Trigonometrik Fonksiyonlar', 'Radyan'], badge: 'AYT Trigonometri', has_turkish: false, is_active: true },
  { slug: 'galton', phet_id: 'plinko-probability', title_tr: 'Galton Tahtası & Olasılık', description: 'Binom dağılımı, normal dağılım yaklaşımı ve olasılıksal simülasyon.', category: 'TYT', subject: 'Matematik', topic: 'Olasılık & İstatistik', difficulty_level: 3, related_yks_topics: ['Olasılık', 'Binom Dağılımı', 'Normal Dağılım'], badge: 'TYT Olasılık', has_turkish: false, is_active: true },
  { slug: 'alan-olusturucu', phet_id: 'area-builder', title_tr: 'Alan Oluşturucu & Geometrik Çevre', description: 'Birim kareler ve çokgenlerle alan-çevre ilişkisi, alan korunumlu şekil deformasyonları.', category: 'TYT', subject: 'Matematik', topic: 'Geometri', difficulty_level: 2, related_yks_topics: ['Alan ve Çevre', 'Çokgenler', 'Birim Kareler'], badge: 'TYT Geometri', has_turkish: false, is_active: true },
  { slug: 'izohips-haritasi', phet_id: 'graphing-slope-intercept', title_tr: 'İzohips Haritası & Kesit Profili', description: 'Eş yükselti eğrileri, tepe, sırt, vadi, falez ve kapalı çukur şekilleri ile dinamik A-B profil kesiti çıkarma.', category: 'TYT', subject: 'Matematik', topic: 'Harita Bilgisi & Topoğrafya', difficulty_level: 3, related_yks_topics: ['İzohips Eğrileri', 'Profil Çıkarma', 'Eğim Hesabı', 'Yer Şekilleri'], badge: 'TYT Banko Soru', has_turkish: false, is_active: true },

  // ─── YENİ SİMÜLASYONLAR (FAZ 2 - 80+ Yeni) ──────────────────────────────
  // FİZİK YENİ
  { slug: 'ohm-kanunu', phet_id: 'ohms-law', title_tr: 'Ohm Kanunu', description: 'Voltaj, direnç ve akım üçgeni ile Ohm Yasasını interaktif grafik üzerinde öğren.', category: 'TYT', subject: 'Fizik', topic: 'Elektrik Devreleri', difficulty_level: 1, related_yks_topics: ['Ohm Yasası', 'Voltaj', 'Akım', 'Direnç'], badge: 'TYT Temel', has_turkish: true, is_active: true },
  { slug: 'faraday-kanunu', phet_id: 'faradays-law', title_tr: 'Faraday Kanunu - EMK', description: 'Bobine yaklaştırılan mıknatısla endüktif EMK, akımın yönü ve Lenz yasasını gözlemle.', category: 'AYT', subject: 'Fizik', topic: 'Elektromanyetik İndüksiyon', difficulty_level: 4, related_yks_topics: ['Faraday Kanunu', 'EMK', 'Lenz Yasası', 'İndüksiyon'], badge: 'AYT Banko', has_turkish: true, is_active: true },
  { slug: 'elektrik-alani', phet_id: 'charges-and-fields', title_tr: 'Elektrik Alanı & Yük Dağılımı', description: 'Nokta yüklerin oluşturduğu elektrik alanı, alan çizgileri ve potansiyel yüzeyleri.', category: 'AYT', subject: 'Fizik', topic: 'Elektrostatik', difficulty_level: 4, related_yks_topics: ['Elektrik Alan', 'Coulomb Kuvveti', 'Elektrik Potansiyeli'], badge: 'AYT Elektrik', has_turkish: true, is_active: true },
  { slug: 'coulomb-kuvveti', phet_id: 'coulombs-law', title_tr: 'Coulomb Kuvveti', description: 'İki yüklü cisim arasındaki elektrik kuvvetini mesafe ve yük büyüklüğüne göre incele.', category: 'AYT', subject: 'Fizik', topic: 'Elektrostatik', difficulty_level: 3, related_yks_topics: ['Coulomb Yasası', 'Elektrik Kuvveti', 'Yük'], badge: 'AYT Elektrik', has_turkish: true, is_active: true },
  { slug: 'newton-cekimi', phet_id: 'gravity-force-lab', title_tr: 'Newton Evrensel Çekim', description: 'İki kütle arasındaki çekim kuvvetini kütle ve mesafeye göre değiştirerek gözlemle.', category: 'AYT', subject: 'Fizik', topic: 'Evrensel Çekim', difficulty_level: 3, related_yks_topics: ['Evrensel Çekim', 'Newton Yasası', 'Gravitasyon'], badge: 'AYT Mekanik', has_turkish: true, is_active: true },
  { slug: 'enerji-bicim-degisim', phet_id: 'energy-forms-and-changes', title_tr: 'Enerji Biçim Değişimleri', description: 'Isı, elektrik, mekanik ve kimyasal enerji arasındaki dönüşümleri interaktif keşfet.', category: 'TYT', subject: 'Fizik', topic: 'Enerji', difficulty_level: 2, related_yks_topics: ['Enerji Dönüşümü', 'Isı Enerjisi', 'Kimyasal Enerji'], badge: 'TYT Fizik', has_turkish: true, is_active: true },
  { slug: 'basinc-akiskan', phet_id: 'under-pressure', title_tr: 'Basınç & Akışkan Mekaniği', description: 'Sıvı basıncı, derinlik, Bernoulli ilkesi ve akışkan hızı ilişkisini keşfet.', category: 'AYT', subject: 'Fizik', topic: 'Akışkanlar', difficulty_level: 3, related_yks_topics: ['Sıvı Basıncı', 'Bernoulli', 'Akışkan Mekaniği'], badge: 'AYT Fizik', has_turkish: true, is_active: true },
  { slug: 'ses-dalgalari', phet_id: 'sound', title_tr: 'Ses Dalgaları & Frekans', description: 'Frekans, genlik, ses hızı ve ortam değişimiyle ses dalgalarını görsel incele.', category: 'TYT', subject: 'Fizik', topic: 'Dalgalar', difficulty_level: 2, related_yks_topics: ['Ses Dalgaları', 'Frekans', 'Desibel'], badge: 'TYT Fizik', has_turkish: true, is_active: true },
  { slug: 'dalga-girisim', phet_id: 'wave-interference', title_tr: 'Dalga Girişimi & Kırınım', description: 'İki kaynaklı girişim deseni, kırınım ve Huygens prensibi deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Dalgalar', difficulty_level: 4, related_yks_topics: ['Dalga Girişimi', 'Kırınım', 'Huygens Prensibi'], badge: 'AYT Optik', has_turkish: true, is_active: true },
  { slug: 'biot-savart', phet_id: 'magnets-and-electromagnets', title_tr: 'Manyetik Alan & Elektromanyetizma', description: 'Düz tel ve bobin etrafındaki manyetik alan çizgileri ile elektromıknatıs deneyi.', category: 'AYT', subject: 'Fizik', topic: 'Manyetizma', difficulty_level: 4, related_yks_topics: ['Manyetik Alan', 'Biot-Savart', 'Elektromıknatıs'], badge: 'AYT Elektrik', has_turkish: false, is_active: true },
  { slug: 'kinetik-kuram', phet_id: 'gas-properties', title_tr: 'Kinetik Gaz Kuramı', description: 'Gaz moleküllerinin hız dağılımı, ortalama kinetik enerji ve sıcaklık ilişkisi.', category: 'AYT', subject: 'Fizik', topic: 'Isı & Termodinamik', difficulty_level: 3, related_yks_topics: ['Kinetik Kuram', 'Maxwell Dağılımı', 'Ortalama Kinetik Enerji'], badge: 'AYT Fizik', has_turkish: true, is_active: true },
  { slug: 'is-guc-enerji', phet_id: 'energy-skate-park-basics', title_tr: 'İş, Güç & Enerji Analizi', description: 'Kuvvet-yer değiştirme grafiği, iş hesabı ve güç-zaman ilişkisi deneyi.', category: 'TYT', subject: 'Fizik', topic: 'Enerji', difficulty_level: 2, related_yks_topics: ['İş Hesabı', 'Güç', 'Verim'], badge: 'TYT Fizik', has_turkish: false, is_active: true },

  // KİMYA YENİ
  { slug: 'periyodik-tablo', phet_id: 'build-an-atom', title_tr: 'Periyodik Sistem & Elektron Dizilimi', description: 'Periyodik tablo, atom numarası, elektron konfigürasyonu ve periyodik özellikler.', category: 'TYT', subject: 'Kimya', topic: 'Periyodik Sistem', difficulty_level: 2, related_yks_topics: ['Periyodik Tablo', 'Elektron Dizilimi', 'Periyodik Özellikler'], badge: 'TYT/AYT Kimya', has_turkish: true, is_active: true },
  { slug: 'kimyasal-tepkime', phet_id: 'reactants-products-and-leftovers', title_tr: 'Kimyasal Tepkime & Stokiyometri', description: 'Mol hesabı, sınırlayan reaktif ve stokiyometrik hesapları interaktif deney.', category: 'AYT', subject: 'Kimya', topic: 'Stokiyometri', difficulty_level: 3, related_yks_topics: ['Mol Hesabı', 'Sınırlayan Reaktif', 'Stokiyometri'], badge: 'AYT Kimya', has_turkish: false, is_active: true },
  { slug: 'cozunurluk-denge', phet_id: 'soluble-salts', title_tr: 'Çözünürlük & Denge', description: 'İyon çarpımı, ortak iyon etkisi ve çözünürlük denge hesapları.', category: 'AYT', subject: 'Kimya', topic: 'Çözünürlük Dengesi', difficulty_level: 4, related_yks_topics: ['Ksp', 'Ortak İyon Etkisi', 'Çözünürlük'], badge: 'AYT Kimya', has_turkish: false, is_active: true },
  { slug: 'asit-baz-ph', phet_id: 'ph-scale', title_tr: 'Asit-Baz & pH Skalası', description: 'pH ve pOH ölçümleri, asit/baz kuvveti ve günlük hayattaki çözeltilerin pH değerleri.', category: 'TYT', subject: 'Kimya', topic: 'Asitler & Bazlar', difficulty_level: 2, related_yks_topics: ['pH Skalası', 'Kuvvetli Asit-Baz', 'Zayıf Asit-Baz'], badge: 'TYT/AYT Kimya', has_turkish: true, is_active: true },
  { slug: 'mol-miktari', phet_id: 'concentration', title_tr: 'Derişim & Mol Hesabı', description: 'Çözünen mol miktarı, hacim ve derişim ilişkisi ile Beer-Lambert deneyimi.', category: 'AYT', subject: 'Kimya', topic: 'Çözeltiler', difficulty_level: 3, related_yks_topics: ['Derişim Hesabı', 'Mol', 'Beer-Lambert'], badge: 'AYT Kimya', has_turkish: true, is_active: true },
  { slug: 'elektroliz', phet_id: 'sugar-and-salt-solutions', title_tr: 'Elektroliz & Elektrokimya', description: 'Elektroliz hücresi, elektrot tepkimeleri ve Faraday yasası ile metalin kaplanması.', category: 'AYT', subject: 'Kimya', topic: 'Elektrokimya', difficulty_level: 4, related_yks_topics: ['Elektroliz', 'Faraday Yasası', 'Elektrot Tepkimeleri'], badge: 'AYT Kimya', has_turkish: false, is_active: true },
  { slug: 'organik-kimya', phet_id: 'molecule-shapes', title_tr: 'Organik Moleküller & Bağ Açıları', description: 'Organik bileşiklerde sp, sp2, sp3 hibritleşme ve 3D yapı.', category: 'AYT', subject: 'Kimya', topic: 'Organik Kimya', difficulty_level: 4, related_yks_topics: ['Hibritleşme', 'Organik Bağlar', 'VSEPR'], badge: 'AYT Organik', has_turkish: true, is_active: true },
  { slug: 'reaksiyon-hizi', phet_id: 'reactions-and-rates', title_tr: 'Reaksiyon Hızı & Aktivasyon Enerjisi', description: 'Sıcaklık, katalizör ve konsantrasyon değişiminin reaksiyon hızına etkisi.', category: 'AYT', subject: 'Kimya', topic: 'Reaksiyon Hızı', difficulty_level: 4, related_yks_topics: ['Reaksiyon Hızı', 'Aktivasyon Enerjisi', 'Katalizör'], badge: 'AYT Kimya', has_turkish: false, is_active: true },

  // BİYOLOJİ YENİ
  { slug: 'gen-ekspresyonu', phet_id: 'gene-expression-essentials', title_tr: 'Gen Ekspresyonu (Transkripsiyon & Translasyon)', description: 'DNA→mRNA transkripsiyon, kodon-antikodon eşleşmesi ve protein sentezi deneyi.', category: 'AYT', subject: 'Biyoloji', topic: 'Genetik & Moleküler Biyoloji', difficulty_level: 4, related_yks_topics: ['Transkripsiyon', 'Translasyon', 'Protein Sentezi'], badge: 'AYT Biyoloji', has_turkish: false, is_active: true },
  { slug: 'mendel-genetigi', phet_id: 'gene-expression-essentials', title_tr: 'Mendel Genetiği & Kalıtım', description: 'Mono ve dihybrid melezlemeler, F1-F2 nesilleri ve Hardy-Weinberg dengesi.', category: 'TYT', subject: 'Biyoloji', topic: 'Kalıtım', difficulty_level: 3, related_yks_topics: ['Mendel Yasaları', 'Dihybrid Melezleme', 'Hardy-Weinberg'], badge: 'TYT Biyoloji', has_turkish: false, is_active: true },
  { slug: 'ekoloji-populasyon', phet_id: 'natural-selection', title_tr: 'Ekoloji & Popülasyon Dinamiği', description: 'Besin ağı, av-yırtıcı ilişkisi, taşıma kapasitesi ve popülasyon büyüme modelleri.', category: 'TYT', subject: 'Biyoloji', topic: 'Ekoloji', difficulty_level: 2, related_yks_topics: ['Besin Ağı', 'Popülasyon Dinamiği', 'Taşıma Kapasitesi'], badge: 'TYT Biyoloji', has_turkish: true, is_active: true },

  // MATEMATİK YENİ
  { slug: 'olasilik-hesabi', phet_id: 'plinko-probability', title_tr: 'Olasılık & İstatistik Temelleri', description: 'Binom dağılımı, Monte Carlo simülasyonu ve temel istatistik hesaplamaları.', category: 'TYT', subject: 'Matematik', topic: 'Olasılık & İstatistik', difficulty_level: 2, related_yks_topics: ['Permütasyon', 'Kombinasyon', 'Olasılık'], badge: 'TYT Matematik', has_turkish: false, is_active: true },
  { slug: 'integral-alan', phet_id: 'calculus-grapher', title_tr: 'İntegral & Alan Hesabı', description: 'Belirli integralin geometrik yorumu, pozitif/negatif alan ve iki fonksiyon arası alan.', category: 'AYT', subject: 'Matematik', topic: 'Analiz', difficulty_level: 4, related_yks_topics: ['Belirli İntegral', 'Alan Hesabı', 'Newton-Leibniz'], badge: 'AYT Analiz', has_turkish: false, is_active: true },
  { slug: 'matris-vektorler', phet_id: 'vector-addition', title_tr: 'Matris & Vektör Dönüşümleri', description: 'Lineer dönüşümler, özvektörler ve matris çarpımının geometrik yorumu.', category: 'AYT', subject: 'Matematik', topic: 'Matrisler', difficulty_level: 5, related_yks_topics: ['Matris', 'Determinant', 'Lineer Dönüşüm'], badge: 'AYT Matematik', has_turkish: false, is_active: true },
  { slug: 'trigonometri-grafik', phet_id: 'trig-tour', title_tr: 'Trigonometrik Fonksiyon Grafikleri', description: 'sin, cos, tan fonksiyonlarının periyot, genlik, faz kayması parametreleri.', category: 'AYT', subject: 'Matematik', topic: 'Trigonometri', difficulty_level: 3, related_yks_topics: ['Trigonometrik Fonksiyonlar', 'Periyot', 'Genlik'], badge: 'AYT Trigonometri', has_turkish: false, is_active: true },
  { slug: 'karmasik-sayilar', phet_id: 'graphing-quadratics', title_tr: 'Karmaşık Sayılar & Kompleks Düzlem', description: 'Karmaşık sayıların geometrik gösterimi, modül-argument ve dönüşümler.', category: 'AYT', subject: 'Matematik', topic: 'Sayı Sistemleri', difficulty_level: 4, related_yks_topics: ['Karmaşık Sayılar', 'Argand Düzlemi', 'Modül'], badge: 'AYT Matematik', has_turkish: false, is_active: true },
  { slug: 'logaritma', phet_id: 'graphing-lines', title_tr: 'Logaritma & Üstel Fonksiyonlar', description: 'Logaritma özellikleri, logaritmik ve üstel fonksiyon grafikleri ve denkleme uygulamaları.', category: 'AYT', subject: 'Matematik', topic: 'Fonksiyonlar', difficulty_level: 3, related_yks_topics: ['Logaritma', 'Üstel Fonksiyon', 'Değişim Oranı'], badge: 'AYT Matematik', has_turkish: false, is_active: true },
];

// Slug'a göre simülasyon bul
export function findSimBySlug(slug: string): PhetSim | undefined {
  return PHET_REGISTRY.find(s => s.slug === slug);
}

// Kategoriye göre filtrele
export function filterPhetSims(params: {
  category?: string;
  subject?: string;
  difficulty?: number;
  search?: string;
}): PhetSim[] {
  let sims = [...PHET_REGISTRY];
  if (params.category && params.category !== 'Tümü') {
    sims = sims.filter(s => s.category === params.category || s.category === 'TYT/AYT');
  }
  if (params.subject && params.subject !== 'Tümü') {
    sims = sims.filter(s => s.subject === params.subject);
  }
  if (params.difficulty && params.difficulty !== 0) {
    sims = sims.filter(s => s.difficulty_level === params.difficulty);
  }
  if (params.search && params.search.trim()) {
    const q = params.search.trim().toLowerCase();
    sims = sims.filter(s =>
      s.title_tr.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q) ||
      s.topic.toLowerCase().includes(q) ||
      s.related_yks_topics.some(t => t.toLowerCase().includes(q))
    );
  }
  return sims;
}
