export interface SimulationItem {
  id: string;
  title: string;
  description: string;
  source_url: string;
  category: 'TYT' | 'AYT' | 'Tümü';
  subject: 'Fizik' | 'Kimya' | 'Biyoloji' | 'Matematik';
  topic: string;
  difficulty_level: number;
  related_yks_topics: string[];
  badge?: string;
  is_active: boolean;
}

export const MASTER_SIMULATIONS: SimulationItem[] = [
  // ─── FİZİK SİMÜLASYONLARI ────────────────────────────────────────────────────
  {
    id: 'sim_doppler',
    title: 'Doppler Etkisi',
    description: 'Hareketli ses kaynağının dalga boyunu sıkıştırması, frekans kayması ve algılanan ses perdesi deneyi.',
    source_url: '/simulasyonlar/doppler-etkisi',
    category: 'AYT',
    subject: 'Fizik',
    topic: 'Dalgalar',
    difficulty_level: 3,
    related_yks_topics: ['Doppler Olayı', 'Ses Dalgaları', 'Frekans Kayması'],
    badge: 'AYT Banko Soru',
    is_active: true
  },
  {
    id: 'sim_sigac',
    title: 'Kondansatör (Sığaç) & Dielektrik',
    description: 'Levhalar arası mesafe, dielektrik madde sokulması; pile bağlıyken ve pilden ayrılınca C, Q, V, E değişimi.',
    source_url: '/simulasyonlar/sigac-kondansator',
    category: 'AYT',
    subject: 'Fizik',
    topic: 'Elektrostatik & Sığaçlar',
    difficulty_level: 4,
    related_yks_topics: ['Sığaçlar', 'Dielektrik Katsayısı', 'Depolanan Enerji'],
    badge: 'AYT Klasik Soru',
    is_active: true
  },
  {
    id: 'sim_fotoelektrik',
    title: 'Fotoelektrik Olayı',
    description: 'Farklı metallere farklı dalga boyunda foton düşürerek elektron sökülmesi ve kinetik enerji hesabı.',
    source_url: '/simulasyonlar/fotoelektrik',
    category: 'AYT',
    subject: 'Fizik',
    topic: 'Modern Fizik',
    difficulty_level: 4,
    related_yks_topics: ['Fotoelektrik', 'Eşik Enerjisi', 'Durdurma Gerilimi'],
    badge: 'Her Yıl 1 Soru',
    is_active: true
  },
  {
    id: 'sim_egik_atis',
    title: 'İki Boyutta Eğik Atış',
    description: 'Başlangıç hızı, atış açısı ve yerçekimini değiştirerek uçuş süresi, menzil ve maksimum yükseklik deneyi.',
    source_url: '/simulasyonlar/egik-atis',
    category: 'AYT',
    subject: 'Fizik',
    topic: 'Kuvvet ve Hareket',
    difficulty_level: 3,
    related_yks_topics: ['Atışlar', 'Eğik Atış', 'Maksimum Yükseklik'],
    badge: 'AYT Mekanik',
    is_active: true
  },
  {
    id: 'sim_young',
    title: 'Young Çift Yarıkta Girişim',
    description: 'Işığın dalga doğası, aydınlık/karanlık saçaklar, yarıklar arası mesafe ve dalga boyu ilişkisi.',
    source_url: '/simulasyonlar/young-deneyi',
    category: 'AYT',
    subject: 'Fizik',
    topic: 'Dalga Optiği',
    difficulty_level: 4,
    related_yks_topics: ['Çift Yarık', 'Saçak Genişliği', 'Kırınım'],
    badge: 'AYT Optik',
    is_active: true
  },
  {
    id: 'sim_harmonik',
    title: 'Basit Harmonik Hareket',
    description: 'Yay sarkacı ve basit sarkaç periyodu, denge konumu, geri çağırıcı kuvvet ve ivme grafikleri.',
    source_url: '/simulasyonlar/harmonik-hareket',
    category: 'AYT',
    subject: 'Fizik',
    topic: 'Basit Harmonik Hareket',
    difficulty_level: 3,
    related_yks_topics: ['Periyot', 'Sarkaç', 'Uzanım'],
    badge: 'AYT Banko',
    is_active: true
  },
  {
    id: 'sim_induksiyon',
    title: 'Manyetik İndüksiyon & Faraday',
    description: 'Manyetik akı değişimi, Faraday indüksiyon yasası ve Lenz kuralı ile akım yönü simülasyonu.',
    source_url: '/simulasyonlar/manyetik-induksiyon',
    category: 'AYT',
    subject: 'Fizik',
    topic: 'Manyetizma',
    difficulty_level: 4,
    related_yks_topics: ['İndüksiyon Emk', 'Lenz Kanunu', 'Manyetik Akı'],
    badge: 'AYT Elektromanyetizma',
    is_active: true
  },
  {
    id: 'sim_elektrik_devresi',
    title: 'Elektrik Devreleri & Ohm Yasası',
    description: 'Seri ve paralel bağlı dirençler, voltmetre ve ampermetre ölçümleri, eşdeğer direnç hesabı.',
    source_url: '/simulasyonlar/elektrik-devresi',
    category: 'TYT',
    subject: 'Fizik',
    topic: 'Elektrik',
    difficulty_level: 2,
    related_yks_topics: ['Ohm Kanunu', 'Eşdeğer Direnç', 'Devre Analizi'],
    badge: 'TYT Banko Soru',
    is_active: true
  },
  {
    id: 'sim_isik_kirilma',
    title: 'Işığın Kırılması & Snell Yasası',
    description: 'Farklı kırıcılık indisine sahip ortamlarda ışığın sapması, sınır açısı ve tam yansıma olayı.',
    source_url: '/simulasyonlar/isigin-kirilmasi',
    category: 'TYT',
    subject: 'Fizik',
    topic: 'Optik',
    difficulty_level: 2,
    related_yks_topics: ['Kırılma İndisi', 'Snell Yasası', 'Tam Yansıma'],
    badge: 'TYT 1 Soru',
    is_active: true
  },
  {
    id: 'sim_kepler',
    title: 'Kepler Gezegen Yasaları',
    description: 'Gezegenlerin eliptik yörüngeleri, alanlar kanunu ve periyotlar kanununun görselleştirilmesi.',
    source_url: '/simulasyonlar/kepler',
    category: 'AYT',
    subject: 'Fizik',
    topic: 'Çembersel Hareket',
    difficulty_level: 3,
    related_yks_topics: ['Kütle Çekim', 'Kepler Kanunları', 'Eliptik Yörünge'],
    badge: 'AYT Fizik',
    is_active: true
  },
  {
    id: 'sim_momentum',
    title: 'Momentum ve Çarpışmalar',
    description: 'Esnek ve esnek olmayan çarpışmalarda momentumun ve mekanik enerjinin korunumu deneyi.',
    source_url: '/simulasyonlar/momentum',
    category: 'AYT',
    subject: 'Fizik',
    topic: 'İtme ve Momentum',
    difficulty_level: 3,
    related_yks_topics: ['Momentum Korunumu', 'İtme', 'Esnek Çarpışma'],
    badge: 'AYT Mekanik',
    is_active: true
  },
  {
    id: 'sim_surtunme',
    title: 'Sürtünme ve Eğik Düzlem',
    description: 'Statik ve kinetik sürtünme katsayısı, eğik düzlem açısı ve net ivme analizi.',
    source_url: '/simulasyonlar/surtunme',
    category: 'TYT',
    subject: 'Fizik',
    topic: 'Kuvvet ve Hareket',
    difficulty_level: 2,
    related_yks_topics: ['Sürtünme Kuvveti', 'Eğik Düzlem', 'Dinamik'],
    badge: 'TYT Fizik',
    is_active: true
  },
  {
    id: 'sim_enerji_parki',
    title: 'Mekanik Enerji Parkı',
    description: 'Kaykay pistinde kinetik, potansiyel ve ısıya dönüşen sürtünme enerjisinin anlık grafikleri.',
    source_url: '/simulasyonlar/enerji-parki',
    category: 'TYT',
    subject: 'Fizik',
    topic: 'İş Güç Enerji',
    difficulty_level: 2,
    related_yks_topics: ['Kinetik Enerji', 'Potansiyel Enerji', 'Mekanik Korunum'],
    badge: 'TYT Temel',
    is_active: true
  },
  {
    id: 'sim_denge',
    title: 'Tork ve Denge Oyunu',
    description: 'Destek noktasına göre moment/tork dengesi, kütle merkezi ve terazi kuralları.',
    source_url: '/simulasyonlar/denge-oyunu',
    category: 'AYT',
    subject: 'Fizik',
    topic: 'Tork ve Denge',
    difficulty_level: 3,
    related_yks_topics: ['Tork', 'Kütle Merkezi', 'Denge Şartları'],
    badge: 'AYT Klasik',
    is_active: true
  },
  {
    id: 'sim_vektorler',
    title: 'Vektörler ve Bileşenler',
    description: 'Kartezyen düzlemde vektör toplama, çıkarma, skaler çarpım ve açı bileşenlerine ayırma.',
    source_url: '/simulasyonlar/vektorler',
    category: 'AYT',
    subject: 'Fizik',
    topic: 'Vektörler',
    difficulty_level: 2,
    related_yks_topics: ['Bileşke Vektör', 'Sinüs/Kosinüs Bileşenleri'],
    badge: 'Temel Fizik',
    is_active: true
  },
  {
    id: 'sim_yay_dalgalari',
    title: 'Yay Dalgaları ve Girişim',
    description: 'Sabit ve serbest uçtan yansıma, dalgaların üst üste binmesi ve atma yayılımı.',
    source_url: '/simulasyonlar/yay-dalgalari',
    category: 'TYT',
    subject: 'Fizik',
    topic: 'Dalgalar',
    difficulty_level: 2,
    related_yks_topics: ['Atma', 'Yansıma', 'Girişim'],
    badge: 'TYT Dalgalar',
    is_active: true
  },
  {
    id: 'sim_radyoaktif',
    title: 'Radyoaktif Bozunma & Çekirdek',
    description: 'Alfa, Beta ve Gama ışıması, kütle numarası ve atom numarası değişim kuralları.',
    source_url: '/simulasyonlar/radyoaktif-bozunma',
    category: 'AYT',
    subject: 'Fizik',
    topic: 'Modern Fizik',
    difficulty_level: 3,
    related_yks_topics: ['Radyoaktivite', 'Alfa Işıması', 'Beta Bozunması'],
    badge: 'AYT Modern',
    is_active: true
  },

  // ─── KİMYA SİMÜLASYONLARI ────────────────────────────────────────────────────
  {
    id: 'sim_titrasyon',
    title: 'Asit-Baz Titrasyonu & pH',
    description: 'Büretle asit-baz damlatma, eşdeğerlik noktası, indikatör renk değişimi ve pH eğrisi.',
    source_url: '/simulasyonlar/titrasyon',
    category: 'AYT',
    subject: 'Kimya',
    topic: 'Asitler ve Bazlar',
    difficulty_level: 4,
    related_yks_topics: ['Titrasyon', 'Eşdeğerlik Noktası', 'pH Hesabı'],
    badge: 'AYT Banko Soru',
    is_active: true
  },
  {
    id: 'sim_le_chatelier',
    title: 'Kimyasal Denge & Le Chatelier',
    description: 'Sıcaklık, basınç ve derişim değişiminde dengenin yön değiştirmesi ve Kc sabitinin davranışı.',
    source_url: '/simulasyonlar/le-chatelier',
    category: 'AYT',
    subject: 'Kimya',
    topic: 'Kimyasal Denge',
    difficulty_level: 4,
    related_yks_topics: ['Dengeye Etki Eden Faktörler', 'Le Chatelier', 'Denge Sabiti'],
    badge: 'AYT Kimya',
    is_active: true
  },
  {
    id: 'sim_ideal_gaz',
    title: 'İdeal Gaz Yasası (P·V = n·R·T)',
    description: 'Gaz moleküllerinin basınç, hacim, mol ve sıcaklık parametreleri ile kinetik teorisi.',
    source_url: '/simulasyonlar/ideal-gaz',
    category: 'AYT',
    subject: 'Kimya',
    topic: 'Gazlar',
    difficulty_level: 3,
    related_yks_topics: ['Boyle Yasası', 'Charles Yasası', 'Kinetik Teori'],
    badge: 'AYT 1 Soru',
    is_active: true
  },
  {
    id: 'sim_piller',
    title: 'Elektrokimyasal Galvanik Piller',
    description: 'Anot ve katot tespiti, standart elektrot potansiyeli, tuz köprüsü ve Nernst denklemi.',
    source_url: '/simulasyonlar/piller',
    category: 'AYT',
    subject: 'Kimya',
    topic: 'Elektrokimya',
    difficulty_level: 4,
    related_yks_topics: ['Galvanik Hücre', 'Pil Potansiyeli', 'Aktiflik'],
    badge: 'AYT Banko',
    is_active: true
  },
  {
    id: 'sim_kcc',
    title: 'Çözünürlük Çarpımı (Kçç) & Çökelme',
    description: 'Doygunluk, ortak iyon etkisi, çökelti oluşumu ve çözünürlük dengesi hesabı.',
    source_url: '/simulasyonlar/kcc-cokelme',
    category: 'AYT',
    subject: 'Kimya',
    topic: 'Çözünürlük Dengesi',
    difficulty_level: 4,
    related_yks_topics: ['Kçç', 'Ortak İyon Etkisi', 'Çökelti'],
    badge: 'AYT Kimya',
    is_active: true
  },
  {
    id: 'sim_molekul_sekil',
    title: 'VSEPR Molekül Geometrisi',
    description: 'Hibritleşme türleri (sp, sp2, sp3), bağ açıları ve molekülün 3D uzay geometrisi.',
    source_url: '/simulasyonlar/molekul-sekilleri',
    category: 'AYT',
    subject: 'Kimya',
    topic: 'Organik Kimyaya Giriş',
    difficulty_level: 3,
    related_yks_topics: ['VSEPR', 'Hibritleşme', 'Bağ Açıları'],
    badge: 'AYT Organik',
    is_active: true
  },
  {
    id: 'sim_atom_olustur',
    title: 'Atom Oluştur & Periyodik Sistem',
    description: 'Çekirdeğe proton ve nötron, katmanlara elektron ekleyerek element oluşturma ve izotoplar.',
    source_url: '/simulasyonlar/atom-olustur',
    category: 'TYT',
    subject: 'Kimya',
    topic: 'Atom ve Periyodik Sistem',
    difficulty_level: 2,
    related_yks_topics: ['İzotop', 'İyon Yükü', 'Elektron Dizilimi'],
    badge: 'TYT Kimya',
    is_active: true
  },
  {
    id: 'sim_maddenin_halleri',
    title: 'Maddenin Halleri & Faz Diyagramı',
    description: 'Katı, sıvı ve gaz tanecik titreşimi, kritik nokta ve üçlü nokta faz geçişleri.',
    source_url: '/simulasyonlar/maddenin-halleri',
    category: 'TYT',
    subject: 'Kimya',
    topic: 'Maddenin Halleri',
    difficulty_level: 2,
    related_yks_topics: ['Faz Değişimi', 'Erime', 'Buharlaşma'],
    badge: 'TYT Temel',
    is_active: true
  },

  // ─── BİYOLOJİ SİMÜLASYONLARI ────────────────────────────────────────────────
  {
    id: 'sim_engelmann',
    title: 'Engelmann Fotosentez Spektrumu',
    description: 'Prizmadan kırılan ışığın ipliksi alg üzerindeki fotosentez hızı ve aerobik bakteri toplanması.',
    source_url: '/simulasyonlar/engelmann-deneyi',
    category: 'AYT',
    subject: 'Biyoloji',
    topic: 'Fotosentez',
    difficulty_level: 3,
    related_yks_topics: ['Engelmann Deneyi', 'Klorofil Soğurması', 'Fotosentez Hızı'],
    badge: 'AYT Klasik Soru',
    is_active: true
  },
  {
    id: 'sim_hucre_zari',
    title: 'Hücre Zarı & Madde Geçişleri',
    description: 'Basit difüzyon, kolaylaştırılmış difüzyon, ozmoz ve aktif taşıma mekanizması simülasyonu.',
    source_url: '/simulasyonlar/hucre-zari',
    category: 'TYT',
    subject: 'Biyoloji',
    topic: 'Hücre ve Organeller',
    difficulty_level: 2,
    related_yks_topics: ['Ozmoz', 'Aktif Taşıma', 'Fosfolipit Tabakası'],
    badge: 'TYT Banko Soru',
    is_active: true
  },
  {
    id: 'sim_fotosentez',
    title: 'Fotosentez & Işık Reaksiyonları',
    description: 'Tilakoit zarda ETS, suyun fotolizi, ATP sentaz ve Calvin döngüsü CO2 fiksasyonu.',
    source_url: '/simulasyonlar/fotosentez',
    category: 'AYT',
    subject: 'Biyoloji',
    topic: 'Fotosentez',
    difficulty_level: 4,
    related_yks_topics: ['Fotoliz', 'Işığa Bağımlı Reaksiyonlar', 'Calvin Döngüsü'],
    badge: 'AYT Biyoloji',
    is_active: true
  },
  {
    id: 'sim_enzim',
    title: 'Enzim Kinetiği',
    description: 'Sıcaklık, pH, substrat derişimi ve inhibitörlerin enzim çalışma hızına etkisi.',
    source_url: '/simulasyonlar/enzim-kinetigi',
    category: 'TYT',
    subject: 'Biyoloji',
    topic: 'Canlıların Temel Bileşenleri',
    difficulty_level: 2,
    related_yks_topics: ['Enzim Hızı', 'Denatürasyon', 'Optimum Sıcaklık'],
    badge: 'TYT Temel',
    is_active: true
  },
  {
    id: 'sim_punnett',
    title: 'Kalıtım & Punnett Karesi',
    description: 'Monohibrit ve dihibrit çaprazlama, genotip ve fenotip oranları, eksik baskınlık.',
    source_url: '/simulasyonlar/punnett',
    category: 'TYT',
    subject: 'Biyoloji',
    topic: 'Kalıtım',
    difficulty_level: 3,
    related_yks_topics: ['Mendel Genetiği', 'Genotip Oranı', 'Çaprazlama'],
    badge: 'TYT 1 Soru',
    is_active: true
  },
  {
    id: 'sim_dogal_secilim',
    title: 'Doğal Seçilim & Popülasyon',
    description: 'Çevre şartları değişiminde kamufle olan bireylerin hayatta kalma ve üreme başarısı.',
    source_url: '/simulasyonlar/dogal-secilim',
    category: 'AYT',
    subject: 'Biyoloji',
    topic: 'Genden Proteine & Evrim',
    difficulty_level: 3,
    related_yks_topics: ['Adaptasyon', 'Seçilim Baskısı', 'Popülasyon Genetiği'],
    badge: 'AYT Biyoloji',
    is_active: true
  },

  // ─── MATEMATİK SİMÜLASYONLARI ────────────────────────────────────────────────
  {
    id: 'sim_turev',
    title: 'Türev & Teğet Doğrusu',
    description: 'Fonksiyon üzerindeki teğet eğimi, anlık değişim oranı ve türev-grafik ilişkisi.',
    source_url: '/simulasyonlar/turev',
    category: 'AYT',
    subject: 'Matematik',
    topic: 'Türev',
    difficulty_level: 4,
    related_yks_topics: ['Teğet Eğimi', 'Artan-Azalanlık', 'Ekstremum Noktalar'],
    badge: 'AYT 4 Soru',
    is_active: true
  },
  {
    id: 'sim_limit',
    title: 'Limit & Süreklilik',
    description: 'Sağdan ve soldan limit yaklaşımı, tanımsızlık noktaları ve grafiksel süreklilik analizi.',
    source_url: '/simulasyonlar/limit',
    category: 'AYT',
    subject: 'Matematik',
    topic: 'Limit ve Süreklilik',
    difficulty_level: 3,
    related_yks_topics: ['Sağ-Sol Limit', 'Süreklilik', 'Belirsizlikler'],
    badge: 'AYT 2 Soru',
    is_active: true
  },
  {
    id: 'sim_birim_cember',
    title: 'Trigonometrik Birim Çember',
    description: 'Açı değişiminde sin, cos, tan ve cot değerlerinin birim çember üzerindeki iz düşümleri.',
    source_url: '/simulasyonlar/birim-cember',
    category: 'AYT',
    subject: 'Matematik',
    topic: 'Trigonometri',
    difficulty_level: 3,
    related_yks_topics: ['Birim Çember', 'Sinüs/Kosinüs', 'İşaret Bölgeleri'],
    badge: 'AYT Banko Soru',
    is_active: true
  },
  {
    id: 'sim_riemann',
    title: 'İntegral & Riemann Toplamı',
    description: 'Eğri altındaki alanın dikdörtgenlere bölünmesi, alt ve üst toplamların integrale yakınsaması.',
    source_url: '/simulasyonlar/riemann',
    category: 'AYT',
    subject: 'Matematik',
    topic: 'İntegral',
    difficulty_level: 4,
    related_yks_topics: ['Riemann Toplamı', 'Belirli İntegral', 'Alan Hesabı'],
    badge: 'AYT 3 Soru',
    is_active: true
  },
  {
    id: 'sim_polinom',
    title: 'Polinom Grafikleri & Kökler',
    description: 'Baş katsayı, polinom derecesi ve çift/tek katlı köklerin x eksenini kesme ve teğetlik davranışı.',
    source_url: '/simulasyonlar/polinom',
    category: 'AYT',
    subject: 'Matematik',
    topic: 'Polinomlar',
    difficulty_level: 3,
    related_yks_topics: ['Kökler', 'Grafik Çizimi', 'Kalan Teoremi'],
    badge: 'AYT 2 Soru',
    is_active: true
  },
  {
    id: 'sim_grafikler',
    title: 'Fonksiyon Grafikleri & Dönüşümler',
    description: 'f(x) fonksiyonunda öteleme, simetri alma, mutlak değer ve ölçekleme hareketleri.',
    source_url: '/simulasyonlar/matematik-grafikleri',
    category: 'AYT',
    subject: 'Matematik',
    topic: 'Fonksiyonlar',
    difficulty_level: 3,
    related_yks_topics: ['Öteleme', 'Dönüşümler', 'Parabol'],
    badge: 'AYT/TYT',
    is_active: true
  },
  {
    id: 'sim_galton',
    title: 'Galton Tahtası & Normal Dağılım',
    description: 'Binom dağılımının çan eğrisine (Gauss normal dağılımı) dönüşmesi ve olasılık simülasyonu.',
    source_url: '/simulasyonlar/galton',
    category: 'TYT',
    subject: 'Matematik',
    topic: 'Olasılık ve İstatistik',
    difficulty_level: 3,
    related_yks_topics: ['Binom Dağılımı', 'Çan Eğrisi', 'Olasılık'],
    badge: 'Olasılık',
    is_active: true
  },
  {
    id: 'sim_kesirler',
    title: 'Kesirler & Görsel Oranlar',
    description: 'Bölünmüş şekiller üzerinde kesir toplama, çıkarma ve denk kesir oluşturma.',
    source_url: '/simulasyonlar/kesirler',
    category: 'TYT',
    subject: 'Matematik',
    topic: 'Temel Kavramlar',
    difficulty_level: 1,
    related_yks_topics: ['Rasyonel Sayılar', 'Kesirler', 'Oran Orantı'],
    is_active: true
  },
  {
    id: 'sim_kuvvet_hareket',
    title: 'Kuvvet ve Hareket (Newton Yasaları)',
    description: 'Sürtünmeli ve sürtünmesiz yüzeylerde net kuvvet, ivme ve kütle ilişkisi (F = m·a).',
    source_url: '/simulasyonlar/kuvvet-ve-hareket',
    category: 'TYT',
    subject: 'Fizik',
    topic: 'Kuvvet ve Hareket',
    difficulty_level: 2,
    related_yks_topics: ['Newton Yasaları', 'Net Kuvvet', 'İvme'],
    badge: 'TYT Banko',
    is_active: true
  },
  {
    id: 'sim_optik',
    title: 'Optik: İnce/Kalın Kenarlı Mercekler',
    description: 'Odak uzaklığı, cisim mesafesi ile görüntü oluşumu, ters/düz ve sanal/gerçek görüntü boyu hesaplayıcı.',
    source_url: '/simulasyonlar/optik',
    category: 'TYT',
    subject: 'Fizik',
    topic: 'Optik',
    difficulty_level: 3,
    related_yks_topics: ['Mercekler', 'Odak Uzaklığı', 'Görüntü Çizimi'],
    badge: 'TYT/AYT',
    is_active: true
  },
  {
    id: 'sim_renk_gorme',
    title: 'Işık Renkleri ve Filtreler',
    description: 'RGB ana ve ara renkler, renkli filtrelerden ışık geçişi ve gözün algıladığı renkler.',
    source_url: '/simulasyonlar/renk-gorme',
    category: 'TYT',
    subject: 'Fizik',
    topic: 'Optik & Renkler',
    difficulty_level: 2,
    related_yks_topics: ['Işık Renkleri', 'Filtreler', 'Kromatik Algı'],
    badge: 'TYT Optik',
    is_active: true
  },
  {
    id: 'sim_yaylar_kutleler',
    title: 'Yaylar ve Kütleler (Hooke Yasası)',
    description: 'Farklı yay sabitleri (k), asılı kütlelerin uzama miktarı, potansiyel enerji ve salınım frekansı.',
    source_url: '/simulasyonlar/yaylar-ve-kutleler',
    category: 'AYT',
    subject: 'Fizik',
    topic: 'Mekanik & Enerji',
    difficulty_level: 3,
    related_yks_topics: ['Hooke Yasası', 'Yay Enerjisi', 'Seri-Paralel Bağlama'],
    badge: 'AYT Fizik',
    is_active: true
  },
  {
    id: 'sim_yari_omur',
    title: 'Çekirdek Kimyası & Yarı Ömür',
    description: 'Radyoaktif izotopların yarı ömrü, zamanla kalan madde yüzdesi ve bozunma eğrisi.',
    source_url: '/simulasyonlar/yari-omur',
    category: 'AYT',
    subject: 'Kimya',
    topic: 'Çekirdek Kimyası',
    difficulty_level: 3,
    related_yks_topics: ['Radyoaktivite', 'Yarı Ömür', 'Bozunma Hızı'],
    badge: 'AYT Kimya',
    is_active: true
  },
  {
    id: 'sim_kati_cisimler',
    title: 'Katı Cisimler (Silindir, Koni, Küre)',
    description: 'Yarıçap ve yükseklik parametreleri ile 3D katı cisim hacmi, yanal alanı ve toplam yüzey alanı.',
    source_url: '/simulasyonlar/kati-cisimler',
    category: 'AYT',
    subject: 'Matematik',
    topic: 'Geometri',
    difficulty_level: 3,
    related_yks_topics: ['Silindir', 'Koni', 'Küre', 'Hacim Hesabı'],
    badge: 'AYT Geometri',
    is_active: true
  },
  {
    id: 'sim_alan_olusturucu',
    title: 'Alan Oluşturucu & Geometrik Çevre',
    description: 'Birim kareler ve çokgenlerle alan-çevre ilişkisi, alan korunumlu şekil deformasyonları.',
    source_url: '/simulasyonlar/alan-olusturucu',
    category: 'TYT',
    subject: 'Matematik',
    topic: 'Geometri',
    difficulty_level: 2,
    related_yks_topics: ['Alan ve Çevre', 'Çokgenler', 'Birim Kareler'],
    badge: 'TYT Geometri',
    is_active: true
  },
  {
    id: 'sim_graham',
    title: 'Graham Gaz Difüzyon Yasası',
    description: 'Cam boru içinde farklı sıcaklık ve mol kütleli iki gazın difüzyon hızı ve karşılaşma noktası.',
    source_url: '/simulasyonlar/graham-difuzyon',
    category: 'AYT',
    subject: 'Kimya',
    topic: 'Gazlar',
    difficulty_level: 3,
    related_yks_topics: ['Gazlarda Difüzyon', 'Graham Yasası', 'Kinetik Teori'],
    badge: 'AYT Klasik Soru',
    is_active: true
  },
  {
    id: 'sim_basit_makineler',
    title: 'Basit Makineler: Makara & Palangalar',
    description: 'Sabit makara, hareketli makara ve palangalarda kuvvet kazancı, yoldan kayıp ve sistem verimi.',
    source_url: '/simulasyonlar/basit-makineler',
    category: 'TYT',
    subject: 'Fizik',
    topic: 'Basit Makineler',
    difficulty_level: 3,
    related_yks_topics: ['Sabit Makara', 'Hareketli Makara', 'Palangalar', 'Verim'],
    badge: 'TYT/AYT',
    is_active: true
  },
  {
    id: 'sim_mayoz',
    title: 'Mayoz Bölünme & Krossing-over',
    description: 'Tetrat, sinapsis, krossing-over varyasyonu, homolog ve kardeş kromatit ayrılması, DNA-kromozom grafikleri.',
    source_url: '/simulasyonlar/mayoz-bolunme',
    category: 'TYT',
    subject: 'Biyoloji',
    topic: 'Hücre Bölünmeleri',
    difficulty_level: 3,
    related_yks_topics: ['Mayoz Bölünme', 'Krossing-over', 'Gamet Oluşumu'],
    badge: 'TYT Banko Soru',
    is_active: true
  }
];
