import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { PlayCircle, Clock, CheckCircle2, TrendingUp, Loader2 } from 'lucide-react';
import ActiveTestModal from './ActiveTestModal';
import TestResultModal from './TestResultModal';

export default function TestsTab() {
  const [pastTests, setPastTests] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Active tests can be dynamically generated by the AI / Backend. For now, empty or mock structure since we don't have active un-submitted tests.
  const activeTests: any[] = [];

  useEffect(() => {
    async function fetchTests() {
      try {
        const res = await fetch('/api/user/tests');
        if (res.ok) {
          const data = await res.json();
          setPastTests(data.sessions || []);
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    fetchTests();
  }, []);

  const [activeTest, setActiveTest] = useState<any>(null);
  const [resultData, setResultData] = useState<any>(null);

  const handleStartTest = (test: any) => {
    setActiveTest(test);
  };

  const handleFinishTest = (score: number, accuracy: number, timeSpent: string) => {
    const data = {
      name: activeTest.name,
      score,
      total: activeTest.questions,
      accuracy,
      timeSpent
    };
    setActiveTest(null);
    setResultData(data);
    // Note: normally we would refetch the pastTests here, but we will just add it locally or reload
  };

  if (loading) {
    return <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '300px' }}><Loader2 className="animate-spin text-purple-500" size={32} /></div>;
  }

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} transition={{ duration: 0.2 }} style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      <div>
        <h2 style={{ fontSize: '1.8rem', fontWeight: 800, color: 'var(--text-primary)', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          📝 Testlerim
        </h2>
        <p style={{ color: 'var(--text-secondary)' }}>Yapay zekanın senin için oluşturduğu eksik kapatma testlerini çöz veya geçmiş başarılarını incele.</p>
      </div>

      <div style={{ display: 'grid', flexWrap: 'wrap', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '2rem' }}>
        
        {/* Active Tests */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: '#ef4444', display: 'inline-block', boxShadow: '0 0 10px #ef4444' }}></span>
            Bekleyen Testler
          </h3>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            {activeTests.length === 0 && (
              <div className="premium-card" style={{ padding: '2rem', textAlign: 'center', color: 'var(--text-secondary)' }}>
                Şu an bekleyen bir testiniz yok. Yeni bir test başlatmak için Soru Çöz modülünü kullanın.
              </div>
            )}
            {activeTests.map(test => (
              <div key={test.id} className="premium-card" style={{ padding: '1.5rem', borderLeft: `4px solid ${test.color}` }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1rem' }}>
                  <div>
                    <div style={{ fontSize: '0.75rem', color: test.color, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '0.25rem' }}>{test.subject}</div>
                    <div style={{ fontSize: '1.1rem', fontWeight: 600, color: 'var(--text-primary)' }}>{test.name}</div>
                  </div>
                  <div style={{ backgroundColor: 'var(--secondary)', padding: '0.25rem 0.75rem', borderRadius: '99px', fontSize: '0.75rem', color: 'var(--text-secondary)' }}>
                    {test.difficulty}
                  </div>
                </div>
                
                <div style={{ display: 'flex', gap: '1.5rem', color: 'var(--text-secondary)', fontSize: '0.85rem', marginBottom: '1.5rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}><CheckCircle2 size={16} /> {test.questions} Soru</div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}><Clock size={16} /> {test.time}</div>
                </div>

                <button 
                  onClick={() => handleStartTest(test)}
                  className="btn-secondary" style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}
                >
                  <PlayCircle size={18} /> Testi Başlat
                </button>
              </div>
            ))}
          </div>
        </div>

        {/* Past Tests */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <TrendingUp size={18} color="#10b981" /> Geçmiş Başarılar
          </h3>
          
          <div className="premium-card" style={{ overflow: 'hidden' }}>
            {pastTests.length === 0 && (
              <div style={{ padding: '2rem', textAlign: 'center', color: 'var(--text-secondary)' }}>
                Henüz tamamlanmış bir testiniz bulunmuyor.
              </div>
            )}
            {pastTests.map((test, i) => {
              const totalQ = test.correct_count + test.wrong_count + test.blank_count;
              const accuracy = totalQ > 0 ? Math.round((test.correct_count / totalQ) * 100) : 0;
              return (
                <div key={test.id} style={{ padding: '1.5rem', borderBottom: i === pastTests.length - 1 ? 'none' : '1px solid var(--border-light)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <div>
                    <div style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--text-primary)', marginBottom: '0.25rem' }}>{test.test_type === 'error_quiz' ? 'Hata Kapatma Testi' : 'Genel Test'}</div>
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{new Date(test.created_at).toLocaleDateString('tr-TR')} • {Math.floor(test.duration / 60)} Dk</div>
                  </div>
                  <div style={{ textAlign: 'right' }}>
                    <div style={{ fontSize: '1.2rem', fontWeight: 800, color: '#10b981' }}>{test.correct_count}/{totalQ}</div>
                    <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Başarı: %{accuracy}</div>
                  </div>
                </div>
              );
            })}
          </div>
          
        </div>

      </div>

      <ActiveTestModal 
        isOpen={!!activeTest} 
        testData={activeTest} 
        onClose={() => setActiveTest(null)} 
        onFinish={handleFinishTest} 
      />

      <TestResultModal 
        isOpen={!!resultData}
        resultData={resultData}
        onClose={() => setResultData(null)}
      />
    </motion.div>
  );
}
